### ISSUE TITLE
Split second GUI flickering (to white, very short time)

### ISSUE THREAD

**Issue by 1proto1** [ArkEcosystem/ark-desktop#1]
I noticed this when running the ArkClient on linux.

Specifics:
Elementary OS 0.4 Loki - 64 bit
Built on Ubuntu 16.04 LTS
Processor: Quad-Core Intel® Core™ i7-6500U CPU @ 2.50GHz
Memory: 7.7 GiB
Graphics:Intel Corporation Sky Lake Integrated Graphics (rev 07), NVIDIA Corporation GM107M [GeForce GTX 960M] (rev a2)

It seems to flicker the window of the client once in a while, whether moving the mouse or not.

**Comment by Doweig** [comment]
Can't reproduce, can you give more information?
