### ISSUE TITLE
Ui

### ISSUE THREAD

**Issue by Moustikitos** [ArkEcosystem/ark-desktop#101]
Horizontal scrollbar is at the bottom of transaction list so I have to scroll down all transactions to scroll them horizontally.

**Comment by fileninja** [comment]
can't reproduce, for me on linux the scrollbar is always pinned on bottom

**Comment by zillionn** [comment]
Moustikitos is your resolution lower than 1024x768? The scroll appears only when window width is lower than 950px.

**Comment by Moustikitos** [comment]
No my res is higher

**Comment by zillionn** [comment]
Then just resize the whole window.

**Comment by Moustikitos** [comment]
![image](https://user-images.githubusercontent.com/15268977/26948271-01454332-4c96-11e7-81e4-1b9bfe0cc655.png)

![image](https://user-images.githubusercontent.com/15268977/26948285-0e816e22-4c96-11e7-873a-7f5ff5332fc4.png)

**Comment by zillionn** [comment]
You need to first disable the screenshot protection from the menu.
