### ISSUE TITLE
Front screen of Desktop doesn't always pull through my account value in currency terms

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#102]
The desktop wallet doesn't always pull through a currency value of the accounts shown on main opening screen of wallet...

Even when you click through to the individual account screen it doesn't show currency value of Ark held.

![image](https://cloud.githubusercontent.com/assets/24484606/25784919/32fa9df6-336d-11e7-93dc-59c3b3adc7e7.png)

If you wait for a period of time, at least a couple of mins and go in and back out to the main screen if updates.... seems to either lag or not update when a connection is found.

Thx

**Comment by fix** [comment]
This is fixed in next version https://github.com/ArkEcosystem/ark-desktop/pull/95
