### ISSUE TITLE
Sending to usernames

### ISSUE THREAD

**Issue by mody199610** [ArkEcosystem/ark-desktop#107]
@fix that can be actually done if we were able to integrate this link into the wallet 

http://explorer.ark.io/api/search?id=

like for an example:
 
http://explorer.ark.io/api/search?id=mody1996 , it will show my address there but i'm no java expert to implement this :D

**Comment by fix** [comment]
Well this is dangerous because subject to phishing attack. And for sure it will be used for phishing.
It would need a protocol update instead where the transaction include the username instead of the address.

I won't fix this on the client, but on a protocol upgrade.

**Comment by fix** [comment]
closing as duplicate, thanks @dafty-1
