### ISSUE TITLE
Vote not showing

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#108]
I told a friend of mine about ARK and he bought some and voted for a delegate.
Address: AYcZyapdFmKnU36tFDQCGJXgYdPC536Kp7

His vote is on the blockchain but not showing in the client. Restarted the client, still no vote. He is using the Windows client.

![ark wallet transactions](https://cloud.githubusercontent.com/assets/3462869/25893373/37599126-3580-11e7-80ed-9ad15a7c802e.jpeg)

![ark wallet votes](https://cloud.githubusercontent.com/assets/3462869/25893378/3bf1a246-3580-11e7-860c-3e1b3f608db4.jpeg)

**Comment by fix** [comment]
Which version of the client? Here i can see the vote to anamix.

**Comment by zillionn** [comment]
1.2.0
Yes, it's on the blockchain but his client is not showing it, not sure why... Maybe if he removes the account and import it this will be fixed but it's not normal.

**Comment by zillionn** [comment]
Video:
https://streamable.com/hw26v

He is using Windows 10 enterprise 64 bit.

**Comment by fix** [comment]
yo thanks, i cannot reproduce but i think somehow the internal storage state has been messed up somehow, ie the vote cannot be stored anymore for some reason.

I think i should make a special button to wipe out all stored data about an account.

**Comment by fix** [comment]
i think this should be solved now. Please reopen the ticket if not @zillionn
