### ISSUE TITLE
ArkClient 1.2.1 - can't send ARK

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#111]
Can't send ARK to valid address, I got this message:
Error: The destination address ... is erroneous

**Comment by zillionn** [comment]
https://github.com/ArkEcosystem/ark-desktop/blob/master/client/app/src/accounts/AccountService.js#L358-L359

???

**Comment by fix** [comment]
yes line 358 is to be removed, forgot in last update, now you should be in the right network version.

Which network settings?

**Comment by zillionn** [comment]
Not sure what you ask me.

**Comment by fix** [comment]
I see the error. on a fix

**Comment by zillionn** [comment]
It works now.
