### ISSUE TITLE
Re-sending unconfirmed tx

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#112]
I had 1 unconfirmed transaction stuck in my wallet. After installing 1.2.1 it automatically send it without even asking me but I already sent that ARK with another tx a week ago!

Not sure that re-sending unconfirmed tx without asking is a good thing...

**Comment by zillionn** [comment]
How about while there are 0 confirmations, show a "resend" button there. When >0 - show the number of confirmations?

**Comment by fix** [comment]
Well now it automatically resends whenever there is 0 confirmation, every 10s or so. no need for button
