### ISSUE TITLE
Built in update option to the main desktop menu.

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#117]
Is it possible to have an update option built into the file menu on the desktop wallet?  there may be a good reason why this can't be enabled, but thought i'd ask.  maybe everyone would be more inclined to update wallets if the function was built in for example.

I read previous issues and couldn't see a similar question.

thanks

jamiec79

**Comment by zillionn** [comment]
There you go:
https://github.com/ArkEcosystem/ark-desktop/pull/118

**Comment by jamiec79** [comment]
nice, thank you.
