### ISSUE TITLE
Refresh disappearens

### ISSUE THREAD

**Issue by axenter** [ArkEcosystem/ark-desktop#12]
Adding a delegate (adding myself) adds the delegate to the vote list but disappears once you refresh.

1. Unchecking them even without refreshing also deletes the delegate.

2. Voting for the person you added before refreshing the app keeps the delegate in place even after refreshing as intended.

**Comment by fix** [comment]
yes, as soon as the vote is not done, it is not saved on the blockchain, thus refreshing remove the votes.
UX should be improved though

**Comment by fix** [comment]
fixed with 0.2.0
