### ISSUE TITLE
Delegates details

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#123]
How about we create a simple page where a delegate will be able to register/verify and write his proposal and the profit sharing details. Then in the desktop/mobile client show that info to the users so they'll be able to choose a delegate a lot easier. Currently 90% of the new users have no idea what voting is and that they can earn some profit. It will also contain a calculator so they can see how much will stack. It will do the same as the excel sheet but inside the ARK client:
https://docs.google.com/spreadsheets/d/1FGo3FkC3uSWXGHatPQyny2brMWjAIJsHFCR-Lhkl_m0/edit#gid=0

Delegate verification could be very simple. Generate a small unique amount and ask them to send that exact amount from the delegate's address to some other address.

**Comment by dafty-1** [comment]
I agree that delegate details & links to proposals is a good idea, but I am
personally not so keen on the profit sharing part.

DPoS makes no reference to profit sharing or pools. In fact, there are a
very small number of pools in Lisk and Shift. This is purely a direction
that the Ark community has taken. The software running the network should
be agnostic and not swayed by "trends" in the community. I am hoping the
network will consist of a range of community, profit share, funds and
side-chain funding delegates in the future. Community tools exist that can
be used to calculate profit sharing rewards.

Using bitcoin.org as an example, it explains the concept of mining and how
to mine, but it doesn't make any reference to pool mining. I believe Ark
should do the same - make proposals accessible, but be neutral when it
comes to why that delegate deserves a spot in the top 51.

I am not passionate either way, but figured I would share my thoughts.

**Comment by zillionn** [comment]
Well then remove that calculator you've created :).

I understand you dafty, and you're probably right, but unfortunately 98% of the investors care only how much they will make and if they know that they will also earn more coins every day, then they will tent to buy and they will buy more. That's my opinion, I could be wrong.

**Comment by zillionn** [comment]
<img width="278" alt="screen shot 2017-05-24 at 20 56 53" src="https://cloud.githubusercontent.com/assets/3462869/26418064/8ea9b05c-40c3-11e7-9796-c34405f2745a.png">

See, that's what people care about, stacking...

**Comment by zillionn** [comment]
Maybe we should move this discussion to the forum or somewhere else. I just wanted the devs opinion.

**Comment by dafty-1** [comment]
Calculator is community project and someone else would have done it if it wasn't me.

I'm debating if Ark should take opinion on what sort of delegates it it wants to run the network, or let the community decide. For people who want to stake, the resources to work it out already exist.

**Comment by barisicm** [comment]
I agree with zillionn, there is no reason that wallet could not have the info about active delegates. From which the user could select, instead of writing the name by themselves. 

We could basically add all the info from the delegate explorer to the desktop wallet. Make all things ark reside inside the wallet.

**Comment by zillionn** [comment]
I have a pull-request to select the delegates from a dropdown menu and it'll probably be available in the next release, but we're talking about the profit sharing details, not only the delegates' usernames.

I'm not sure if it's right to include the profit sharing details in the client, that's why it's probably better to move this to the forum and ask for more opinions.
