### ISSUE TITLE
Delay start payment after delegate vote

### ISSUE THREAD

**Issue by flokanda** [ArkEcosystem/ark-desktop#132]
Hello,
I voted for the delegate arkpool for two days and have not yet received any payment (settlement announced every 6h). Is there a timeout or is this a bug? What can I do to unlock...
Previously I had voted for another without problem. I followed the procedure of unvote and new vote, which seems to have gone correctly.
Thank for your help.

**Comment by boldninja** [comment]
You should contact arkpool delegate owner (best in Ark slack) - delegates are community members and Ark team cannot assist you in this matter.

**Comment by flokanda** [comment]
Thanks ! I do this... and sorry for this error.

**Comment by fix** [comment]
yes this is not linked to this software, but to the delegate. Closing as it is unrelated.
