### ISSUE TITLE
Add second passphrase option

### ISSUE THREAD

**Issue by axenter** [ArkEcosystem/ark-desktop#14]

**Comment by jamiec79** [comment]
what type of 2 factor authentication will be used? sms, call, Clef?

**Comment by Doweig** [comment]
He was referring to a second passphrase like in LISK. You need 1 passphrase to "open" your wallet and a second to do actions like vote of send transactions.

**Comment by Suxuss** [comment]
yes..Is there any option for second pass for send transaction

**Comment by fix** [comment]
yes this is a bug for the last release, it disapeared for some reason. We are working on a hot fix
