### ISSUE TITLE
Filter to see Vote Rewards

### ISSUE THREAD

**Issue by Arckanum1** [ArkEcosystem/ark-desktop#149]
Hi, please can we have a filter in the wallet, to show Ark Received from Vote rewards (Or even just from a specific person, if that is easier. Infact, yeah, that would be better, especially if you switch delegates at some point). 
Then also have a count to show the Total amount received from said person?

**Comment by fix** [comment]
mmm interesting, we have to think about the best UX for this. But won't be ready for the upcoming 1.3.0 release

**Comment by luciorubeens** [comment]
You can use the feature implemented in #216
