### ISSUE TITLE
Protecting users from making a 'non standard passphrase'

### ISSUE THREAD

**Issue by AbeIgnocious** [ArkEcosystem/ark-desktop#151]
Currently when making a new address, a 12 word passphrase is shown. This makes the user believe that the standard accepted format is 12 words separated by spaces. However any string can be used to generate an address. 

I think it might be better to add a checkbox, something like [ ] allow custom passphrase, and only if that is checked does it allow a non 12 word string. This helps with awareness of how the passphrases work, and also helps in case of typos. Right now if one of the 12 words contains a typo, a new address is generated, containing obviously 0 ark. This could potentially scare non technical adopters.

I also propose to add a text popup when the custom passphrase checkbox is checked, containing a short explanation on the standard generated 12 word passphrase format, and why a new address is generated when a typo is in the passphrase

Regards

Charles

**Comment by fileninja** [comment]
As I see, you actually cant even put an custom passphrase in the desktop wallet. So this one here means to implement custom passphrase feature first and solving this with the mentioned design decision.
Problem would be the actual verifiying step (word 3, 6, 9) which indeed needs another verifying dialog for custom passphrases.
@fix is this feature wanted?

**Comment by luciorubeens** [comment]
@fileninja In fact it is currently possible to use a custom passphrase, just enter the password you want in Import Account.. Maybe include a message indicating this possibility, but I think it is rather insecure

**Comment by fix** [comment]
@fileninja yes use import account if you have a custom passphrase.

**Comment by fix** [comment]
1. this is fixed in upcoming version thanks to https://github.com/ArkEcosystem/ark-desktop/pull/116
2. If you want to bypass this bip39, feel free to use "import account".

Closing it. @fileninja and @AbeIgnocious feel free to reopen it if you feel i miss a point
