### ISSUE TITLE
Could a Payment script/tab be built into Desktop wallet?

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#158]
Would it be possible to have a payment script built into the desktop wallet?

You would select the account, define the share parameters (x% to voter etc) and run the script?

It would ask for one or both phrases and run.

Just a thought..

**Comment by fileninja** [comment]
can you give further informations what should be done exactly?
this is my understanding of your request:
1. the payment tab should build for each address which is an delegate
2. with passphrase you verify that its your account(or its already imported)
3. in this tab you see your actual share parameters and can change (and save for sure) them
is this correct?

**Comment by jamiec79** [comment]
Yeah I was suggesting a pool payout script linked to the desktop wallet. Select your %age split parameters, which addresses the shares need paying to. Similar to toons arky desktop, but built into the wallet to simplify things.

**Comment by zillionn** [comment]
The sharing delegates are no more than 20-30, the desktop client is used by thousands. Also sharing the rewards is a community thing it should be separated.

However, a link to the delegates proposals will be handy for the users.

**Comment by jamiec79** [comment]
Oke no probs, just close the issue.

Thx

Sent from my iPhone

On 17 Jul 2017, at 10:09, zillionn <notifications@github.com<mailto:notifications@github.com>> wrote:


The sharing delegates are no more than 20-30, the desktop client is used by thousands. Also sharing the rewards is a community thing it should be separated.

However, a link to the delegates proposals will be handy for the users.
