### ISSUE TITLE
Add Icon to Change Token Network & Add Signing of Messages

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/ark-desktop#160]
Currently its not evident on how to change network ( mainnet / devnet or any other custom networks) + testnet should be deleted by default (since it was replaced with devnet).

Solution : Add icon in the right upper menu, when clicked it shows all networks you have saved (reads from manage networks)

![networks](https://user-images.githubusercontent.com/25795454/27949030-584c61de-62fc-11e7-9d0f-6862216732b3.png)

Adding signing of messages within Ark Desktop - currently its only possible through ARK CLI ( https://github.com/ArkEcosystem/ark-client/blob/master/index.js#L628 )

![signverify](https://user-images.githubusercontent.com/25795454/27948766-4802a992-62fb-11e7-97c5-c76b57e9655f.png)

**Comment by fix** [comment]
true that, can you put into 2 separate issues, to better track them down

**Comment by fileninja** [comment]
@fix not needed because both issues are solved already :laughing:

**Comment by zillionn** [comment]
@fix the ninjas are taking over :)

**Comment by fileninja** [comment]
@zillionn but that ninjas are awesome ninjas :D

**Comment by boldninja** [comment]
![giphy 2](https://user-images.githubusercontent.com/25795454/28080171-3fa9ad2c-666b-11e7-9aa4-f01d612f134b.gif)

**Comment by fix** [comment]
🥋
