### ISSUE TITLE
Cannot build/run macOS 10.12.x

### ISSUE THREAD

**Issue by sleepdefic1t** [ArkEcosystem/ark-desktop#170]
1.2.2 builds and runs no issues.

1.3.0 after #167; various permissions and dependency issues.

#
node 6.9.2 - Blank Electron Window; permission errors in 'dev tools'  

![screen shot](https://user-images.githubusercontent.com/7477456/28212568-11fc772c-6870-11e7-8a92-e4af507bb168.png)  

#
node > 8  
![screen shot 2017-07-13 at 10 57 24 pm](https://user-images.githubusercontent.com/7477456/28212616-394e3ec8-6870-11e7-851f-d1fac1978b24.png)

# 

Tried 
```bash
npm rebuild --runtime=electron --target=1.6.11 --disturl=https://atom.io/download/atom-shell --build-from-source
```

Same results.

**Comment by fix** [comment]
ok reproduced on a clean new install

**Comment by fix** [comment]
@sleepdefic1t i let you close this issue
