### ISSUE TITLE
Unvoting error

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#176]
When I unvote someone occasionally it says invalid time stamp. So I update internet time, go back to unvote again and it already unvoted.

So it seems like even though it displays the error message about timestamp it does process the unvote?

**Comment by jamiec79** [comment]
I'll try to replicate and screen shot it 🙂

**Comment by zillionn** [comment]
The client is re-sending the unconfirmed txs. That's probably what's happening.

**Comment by fix** [comment]
yes, this is what happens, if it did not get through it will automatically resend until got through

I will fix the issue at protocol level (ie on ark-node). Closing this
