### ISSUE TITLE
Plugin / Script support for desktop

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-desktop#180]
We should provide plugin/extension and script support for the desktop.

It would be really great to be able to write and distribute simple extensions of the desktop.

Then you could easily automate stuff and build things into/ontop of the desktop client.

Would allow the desktop client to become the hub for all kind of tools.

You could then also include profit sharing/optimisaiton overviews as an example

**Comment by fileninja** [comment]
I really like the idea. With this er Should provide an Plug-in/Script API. Maybe the ark-js functions or something Complete new

**Comment by fix** [comment]
while the idea is definitely nice, this raise the issue of trusting 3rd part script/plugin, as we (ark team) will not have a full control of what the scripts will be doing...

not sure what the best option

**Comment by fileninja** [comment]
generally i would say the user has to check what type of script he loads and if it has malicious backgrounds. We should really hardl define what type of events goes out and what functions we expose.

**Comment by Zeehenk** [comment]
Hi everyone,

I'm a total n00b with coding (read: I can't do it at all), but I would like to see what's possible with this request. Firstly my issue:

I have voted for a delegate, but this dalegate has capped my max voting weight. This means that I have made a second wallet for voting with my remaining ARK.
I am getting weekly payments by the first delegate to my "capped wallet", but I want to get this payout to my second walled directly. What I would like to set up are some rules like I can do with Outlook. For example for this:

If ARK received from

, than to
I think this would be a great feature for people (like me) who can't code. Even one line of code seems scary for me to do... I'm too afraid to make mistakes in there and lose my ARK.

Obviously this "RULE" feature is not limited to above example. You could have rules to only send ark if you received an X amount from a particular address etc....

Hope I explained everything well enough :)

Cheers!

Kind of the same topick here:
(https://github.com/ArkEcosystem/ark-desktop/issues/202#issuecomment-322736785)

**Comment by zillionn** [comment]
To accomplish this you need to save your passphrase for address A in the wallet/plugin so it can send ARK from address A to B. Saving the passphrase is a very bad idea.

**Comment by sleepdefic1t** [comment]
@Jarunik @fix @fileninja @zillionn 

If you think of ArkClient as a backend in this scenario, 
it can basically become an RPC client.


Or even a simple App URI could open a transaction request.
`arkclient://transaction/create?recipientId=AxX...Xx&amount=100000000&vendorField=......`

I have a friend learning and trying to do a "pay with Ark" button for websites;
he was trying to figure out how to have the user sign the TX in-browser.

I told him it'd be much better to have it launch the Ark Desktop Client,
since we don't want anyone in the habit of transmitting sensitive info.

**Comment by luciorubeens** [comment]
- Basic plugin loader implemented in #207
- URI handler implemented in 1.5.1
