### ISSUE TITLE
Slightly increase dashboard boxes' opacity

### ISSUE THREAD

**Issue by gmpryb** [ArkEcosystem/ark-desktop#183]
I was looking through different themes and noticed, in particular, the "ahoy" theme didnt mesh well with the opacity of the list of "accounts" box and the "market"/"network" boxes sitting below it. 

I really like that its slightly transparent but possibly increasing the opacity just a few percentages would fix this issue, in my opinion.

Great job on the wallet overall though, looks great!
![dashboard_opacity](https://user-images.githubusercontent.com/28497279/29059736-efdf6ff4-7be4-11e7-8e88-4d4ce5afed0f.JPG)

**Comment by j-a-m-l** [comment]
The buttons are a problem too:
![alchemy-buttons](https://user-images.githubusercontent.com/1161224/30632205-99d102b0-9de7-11e7-976b-482d8b7b5c15.png)

I've been reviewing this and I think that it could be done:
1. Changing the transparency of those elements
2. Using a different colour+transparency for some lighter textures, such as "Ahoy" and "Alchemy".

What do you think?

**Comment by fix** [comment]
yes there is definitely some improvements to do in that respect.
Also moving the Appearance into its own component would be great.

**Comment by j-a-m-l** [comment]
I think that I'd create a simple configuration object, like [themes](https://github.com/ArkEcosystem/ark-desktop/blob/2fe45c887a9d34436bd01a63495e67d086d8752b/client/app/app.js#L5).

So, there would be a default configuration (that wouldn't change anything of the current aesthetics), but there would be an option for using a custom CSS class for specific background colours or textures.

@fix do you think this approach it's OK or do you have any suggestions about it?

**Comment by fix** [comment]
Sounds good to me! You can go ahead

**Comment by alexbarnsley** [comment]
@luciorubeens you merged this manually - can it be closed?
