### ISSUE TITLE
Make My Accounts and Add / Import "Static" on Main

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/ark-desktop#186]
![scroll](https://user-images.githubusercontent.com/25795454/29073647-b36be53a-7c4c-11e7-8a0b-8a598332c701.jpg)

If you have more accounts (so that scrollbar becomes visible) on the main menu if you scroll down the "My Accounts" stays up and is not visible - maybe would be better if that is seperate and visible even as you scroll down of your Ark accounts and maybe move import address there as well.

![scroll1](https://user-images.githubusercontent.com/25795454/29073734-00b805ee-7c4d-11e7-84bb-a07a0426a8a6.jpg)

Possible solution:

![solution](https://user-images.githubusercontent.com/25795454/29073915-bcc79286-7c4d-11e7-81ab-c365a4cd7661.jpg)

**Comment by fix** [comment]
you fired :)

**Comment by boldninja** [comment]
no, why me :'(

**Comment by fileninja** [comment]
You're a hell of a ninja.. finding things anyone else without eagle eyes would even notice
