### ISSUE TITLE
Import signed messages to verify

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-desktop#187]
Currently you have to copy/paste 3 fields to verify a signed message.

It would be easier to be able to import the entire signed message as well:

{"publickey":"02c7455bebeadde04728441e0f57f82f972155c088252bf7c1365eb0dc84fbf5de","signature":"30450221008ad2cfe1dc76a90758ed84856036baf42d8713f5d889ad237154468348dfceeb022010732eeb5725e98f3677e584e533f4442c048013591fcd371a3dc81c41961490","message":"Thanks a lot to all my voters for your support. Jarunik"}

**Comment by fix** [comment]
true that

**Comment by luciorubeens** [comment]
Fixed in #200
