### ISSUE TITLE
Display public key

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-desktop#188]
It would be good if you can see the public key of your account somewhere in the desktop client.

**Comment by fix** [comment]
good = use case.
Which use case?

**Comment by boldninja** [comment]
To sign/verify message you need to find public key of the signer and if someone tries to sign a message he needs to find his public key to relay it to the one who wants to verify message. Currently the only way is to go to explorer, input ARK address and see public key on explorer so would be more convenient to have an option or small icon - reveal public key.

**Comment by luciorubeens** [comment]
Solved 349fba67644bc18b8a9e079ef0a91b29dc104e1b.
