### ISSUE TITLE
Unable to send ark

### ISSUE THREAD

**Issue by virgolus** [ArkEcosystem/ark-desktop#189]
I've tried to send a small amount of my ark to my bittrex account, but I've this error in console:

```
http://37.59.129.163:4001/peer/transactions
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

The GUI doesn't return any error, but no transaction was created.

arkClient version: 1.3.0
macOS Sierra v 10.12.6 (latest)

**Comment by fix** [comment]
This is ususally harmless (ie some nodes may be down or have issues). The tx is usually braodacsts to 10 different nodes. Can you give me the id of the tx?

**Comment by fix** [comment]
this one https://explorer.ark.4miners.net/tx/9fd733f7a8d4bb242e40f577b93cdc3465ad50f8aa12da5eb33d330f17843c74 ?

**Comment by virgolus** [comment]
I do not see any transaction. Only the first one, after the ICO

My public key is ASCiSVKBaWkursZj8sVXGb71eiWYNm16dP

https://explorer.ark.io/address/ASCiSVKBaWkursZj8sVXGb71eiWYNm16dP

**Comment by fix** [comment]
mmm definitely a bug. could you reproduce it?

**Comment by fix** [comment]
ok i know what happened:
if a tx is refused by a node it is deleted and not broadcasted. I should think about a better strategy if return code is different from 200 (ie node has an issue, not the tx)

**Comment by virgolus** [comment]
Sorry for my late response.
I've retried to make a transaction, opened dev tools and find this json as response:

```
{
  "success": false,
  "message": "Request is made on the wrong network",
  "expected": @an hashcode different from mine@
  "received": "@my current nethash@"
}
```
What does "Request is made on the wrong network" mean? I've a wrong network configuration? I've a wrong nethash?

From "manage networks":
seed server: http://91.134.115.26:4001

**Comment by boldninja** [comment]
@virgolus what nethash you have for "Mainnet" ?

Should be : 6e84d08bd299ed97c212c886c98a57e36545c8f5d645ca7eeae63a8bd62d8988

**Comment by virgolus** [comment]
a different one, obiuvsly :)

Is safe to change my nethash?

**Comment by boldninja** [comment]
You need to have 6e84d08bd299ed97c212c886c98a57e36545c8f5d645ca7eeae63a8bd62d8988  set as Mainnet hash, else it will throw the error you get since you are signing transactions on wrong network (not same nethash). So copy paste this one and click save.

**Comment by virgolus** [comment]
It works!

thank you for the support

**Comment by fix** [comment]
mmm, are those both issues somewhat related?

**Comment by j-a-m-l** [comment]
It looks that this issue could be closed. @virgolus if you think that is still a problem, re-open it.

**Comment by mastah12322** [comment]
Hi , i have reinstaled the arc on my server, my question is can i set a custom nethash ? the old ? or this is not posibil ??
