### ISSUE TITLE
Frame around Desktop client

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#19]
UI - when using a black background it merges into the Arc desktop image, difficult to see which is which

Possibly a frame around the client would help distinguish between the two?

**Comment by fix** [comment]
yes this is done on purpose, you don't like it?

**Comment by jamiec79** [comment]
I like it, if i wasn't using a default black background then it would look great. 

But i guess it's not possible to auto frame if desktop back ground is black

**Comment by Doweig** [comment]
Can't reproduce, can you attach a screenshot maybe?

**Comment by jamiec79** [comment]
![image](https://cloud.githubusercontent.com/assets/24484606/24319550/173a723a-1117-11e7-9494-afa1d96874c5.png)

**Comment by jamiec79** [comment]
![image](https://cloud.githubusercontent.com/assets/24484606/24319563/612d3a08-1117-11e7-8470-ff40b3f5dfb5.png)

![image](https://cloud.githubusercontent.com/assets/24484606/24319565/6b5855c6-1117-11e7-9d11-234a94ed33c2.png)

**Comment by Doweig** [comment]
ok, got it
