### ISSUE TITLE
ArkClient integrity (code signing/checksum)

### ISSUE THREAD

**Issue by koenbud** [ArkEcosystem/ark-desktop#191]
Yesterday I installed ArkClient 1.3.0 and I was unable to find the checksums to verify the integrity of the binaries. Now I can only hope I have the actual untampered client (which probably is the case).

I am not a security expert, but code signing the binary would be even better I think, because that enables users to both verify the integrity and authenticity.

**Comment by fix** [comment]
yes definitely a best practice we should adopt. We plan to register sha256 of binary on the blockchain.

**Comment by luciorubeens** [comment]
Hi @koenbud, thanks for the suggestion! Added to the latest release.

**Comment by koenbud** [comment]
Awesome, thanks!
