### ISSUE TITLE
Desktop Client Icons

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#20]
The icons top right of desktop. they don't see to have any descriptions to identify them.

I know when you click on them you are provided with options, but for ease of use, either a description below it or it if you hover over the button they identify themselves.

The one icon looks like a wifi signal, which i think relates to peer and block height info.

Hopefully these points are helpful...? :-/

**Comment by fix** [comment]
yes will rethink the icon. I liked the wifi icon because it tells intantly if you are connected or not to ark network...

**Comment by jamiec79** [comment]
I agree the wifi logo works, but from non techhie point of view people would just associate that with their own home wifi connection

Also there doesn't appear to be a maximise minimise option on the desktop client, it's either 3/4 screen or nothing.  Could the minimised version show a summarised version of the the desktop client

**Comment by Doweig** [comment]
<img width="412" alt="screen shot 2017-03-23 at 10 51 53 pm" src="https://cloud.githubusercontent.com/assets/1850848/24253452/5bacd388-101b-11e7-8b6e-c7fe451b728d.png">
<img width="426" alt="screen shot 2017-03-23 at 10 50 12 pm" src="https://cloud.githubusercontent.com/assets/1850848/24253453/5bb80f0a-101b-11e7-8944-d63791b2785a.png">

**Comment by jamiec79** [comment]
Very nice d00d 👍

Sent from my iPhone

On 23 Mar 2017, at 14:52, Guillaume Verbal <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2017-03-23 at 10 51 53 pm]<https://cloud.githubusercontent.com/assets/1850848/24253452/5bacd388-101b-11e7-8b6e-c7fe451b728d.png>

[screen shot 2017-03-23 at 10 50 12 pm]<https://cloud.githubusercontent.com/assets/1850848/24253453/5bb80f0a-101b-11e7-8944-d63791b2785a.png>

**Comment by fix** [comment]
nice, like it!
