### ISSUE TITLE
Horizontal scrolling bar can't be moved

### ISSUE THREAD

**Issue by ravelou** [ArkEcosystem/ark-desktop#204]
The horizontal scrolling bar in "my account" view is only be movable if your at the bottom of the transaction page. It would be better if it can be movable even at the top position so that we can see long smartbridge.
![image](https://user-images.githubusercontent.com/6950459/29365703-3c7deeb2-8298-11e7-8d27-5949a62e6760.png)

**Comment by luciorubeens** [comment]
Fixed in #236
