### ISSUE TITLE
account creation issue

### ISSUE THREAD

**Issue by ffiresticks** [ArkEcosystem/ark-desktop#205]
Hi , I downloaded the ark client 1.3 to windows and when I try to create an account nothing happens after i enter the 3rd, 6th and 9th word of the passphrase. The dialog box just closes and thats it??

**Comment by boldninja** [comment]
Doesn't it open your ARK account you created?

**Comment by ffiresticks** [comment]
No, so I downloaded the client. Clicked create account. Saved and added the three words of the passphrase when prompted then the dialog box just closes and nothing happens


Sent from Mail for Windows 10

**Comment by boldninja** [comment]
You can click on "import account" and paste that 12 word passphrase and it should open it, but make sure you have passphrase saved somewhere as that will be your access to that specific Ark address - if you lose it you lose access to that Ark address and any Ark you will be sending on that Ark address.

**Comment by ffiresticks** [comment]
Yeah, I had already tried that work around. Again nothing happens. Just tried it once more after yor response. Same thing. 

Sent from Mail for Windows 10

**Comment by boldninja** [comment]
Can you make screenshot on what it does (don't forget to click on Application in the upper left menu -> Disable Screenshot protection) ?

**Comment by ffiresticks** [comment]
Same thing. No account is created. 3 Pics included pre-create; three word ; post create

Also fyi, just updated to 1.3.1. No luck. Same problem

Sent from Mail for Windows 10

From: Frederico Fernandes
Sent: Wednesday, August 16, 2017 10:00 AM
To: ArkEcosystem/ark-desktop
Subject: RE: [ArkEcosystem/ark-desktop] account creation issue (#205)

Yeah, I had already tried that work around. Again nothing happens. Just tried it once more after yor response. Same thing. 

Sent from Mail for Windows 10

**Comment by ffiresticks** [comment]
Yes

**Comment by ffiresticks** [comment]
I'm on a Microsoft surface if it makes any difference.

**Comment by luciorubeens** [comment]
please, try again and after dialog box closes, press Ctrl + D and put screenshot here (directly in github)

**Comment by ffiresticks** [comment]
![ark post create w code](https://user-images.githubusercontent.com/31070669/29376135-936a6fb0-8285-11e7-9054-76403c740772.PNG)

**Comment by fileninja** [comment]
we need the **Console Tab** in that Ctr +D Window to see the errors.
can you do that again please?

**Comment by ffiresticks** [comment]
![ark console tab](https://user-images.githubusercontent.com/31070669/29384405-f0252314-82a1-11e7-851f-9b3552826016.PNG)

I never closed the ark client so this is still the same account i tried to create when i sent the last picture

**Comment by ffiresticks** [comment]
Hey dont know why but its suddenly working now. Thanks

**Comment by luciorubeens** [comment]
Great!
