### ISSUE TITLE
Message verification form doesn't return error with wrong data

### ISSUE THREAD

**Issue by biolypl** [ArkEcosystem/ark-desktop#206]
Try insert this values in message verification form and click verify:
Message: 30450221008ad2cfe1dc76a90758ed84856036baf42d8713f5d889ad237154468348dfceeb022010732eeb5725e98f3677e584e533f4442c048013591fcd371a3dc81c41961490
Public Key:
02c7455bebeadde04728441e0f57f82f972155c088252bf7c1365eb0dc84fbf5de
Signatur:
Thanks a lot to all my voters for your support. Jarunik

Wallet hangs for me. Another combinations return "normal" error

**Comment by fileninja** [comment]
true that. there was a mistake for not checking the input against hexadecimal so it was'nt possible to convert it to hex and with that no return happened.

**Comment by fileninja** [comment]
there you go

**Comment by luciorubeens** [comment]
Fixed in #212
