### ISSUE TITLE
Add "Broadcast Offline Generated TX" window

### ISSUE THREAD

**Issue by bhaaltazar** [ArkEcosystem/ark-desktop#213]
Can you please add feature to be possible to sign transaction on offline computer and send it signed online? It will give much more security level.

**Comment by fix** [comment]
yes you can do it in the console for now, details coming

**Comment by fix** [comment]
ok so to handle offline:
- turnoff your internet connection
- create transaction in the client
- sign it with the passphrase
- when a popup put the summary of the signed transaction before sending it, turn on internet connection
- hit send button

Is this the Use Case you had in mind?

**Comment by fix** [comment]
@bhaaltazar if you want to create a transaction and sign on another computer then put it in usb key and then send it, there are also solutions, let me know exactly the use case.

**Comment by bhaaltazar** [comment]
@fix yes, i'd like to sign on other computer. Need smth like this https://www.myetherwallet.com/#offline-transaction

**Comment by bhaaltazar** [comment]
I tried ark-java to generate json transaction, then import from json using Transaction.fromJson and it works

**Comment by boldninja** [comment]
@fix thinking out loud - maybe for ease of use we should add a window in Ark Desktop "Broadcast Offline Generated TX" where you can paste offline json data and broadcast it to the network.

**Comment by bhaaltazar** [comment]
@boldninjs yes, "Broadcast Offline Generated TX" in wallet is a good idea

**Comment by fix** [comment]
yo +1, sounds a really sensible UX.

**Comment by fix** [comment]
changed title for clarity

**Comment by fix** [comment]
@bhaaltazar in the between you can do the following:
- create your signed tx offline
- in the client: ctrl+d (opening dev console)
- write:
```
tx={your signed transaction in json format};
angular.element(document.body).injector().get('networkService').postTransaction(tx);
```

**Comment by bhaaltazar** [comment]
@fix it works, thank you
