### ISSUE TITLE
Can't start windows application : Javascript error

### ISSUE THREAD

**Issue by remiheens** [ArkEcosystem/ark-desktop#214]
I've just download Win32 application from this repository but it can't start.

It throw "A Javascript error occured in the main process" with an Exception "%1 nest pas une application win32 valide."

![capture](https://user-images.githubusercontent.com/1227400/29483773-aa751706-84af-11e7-9554-c417ed4a7430.PNG)

How can I fix that & launch & enjoy my Ark ?

----  
Application version : 1.3.1
Windows 8 (32bits)

**Comment by fix** [comment]
mmm we had this issue in the past
@luciorubeens can you reproduce on a virtual machine somehow?

**Comment by fix** [comment]
@remiheens can you try downloading previous version win32 1.3.0 if it works?

**Comment by luciorubeens** [comment]
I built a new release to Win32. @remiheens please download it again.

**Comment by remiheens** [comment]
@luciorubeens yep, this release fix the problem, I can start Win32 client & enjoy it :) thx
