### ISSUE TITLE
Account "vault/bank" image showing, even without 2nd passphrase

### ISSUE THREAD

**Issue by gmpryb** [ArkEcosystem/ark-desktop#215]
I was responding to someone telling me that 2nd passphrase creation does not tell you about the 5 ARK fee, so when I was testing it myself on an account without any ARK in it, I ran into something buggy.

1. I clicked the 2nd passphrase activation and it gave me the passphrase.
2. I clicked create and it asked for my original passphrase along with the new 2nd one. 
3. I clicked cancel.

Even though I clicked cancel it still showed the image(bank/vault/pillar thing) on the left, next to the account address that shows whether you have a 2nd passphrase activated.

The weird this is: this only worked with accounts that once had ARK in it, but no longer does. I tried it with a brand new account, one without any transactions, and it didn't work.

**Comment by gmpryb** [comment]
Also, I restarted multiple times and it still showed the 'vault' image. When I tried went to one of the accounts with the 'vault' image and clicked to set up a 2nd passphrase, it gave me a new one; this new phrase was different from the initial one I tested with.

**Comment by fix** [comment]
vault/bank is showing when the publickey is known, ie some transactions has been made from the account. Otherwise it is a cold account.

**Comment by gmpryb** [comment]
Okay. So why is it only showing the image after I click '2nd passphrase', but not before I do this?

**Comment by fix** [comment]
i guess it needs time to refresh, so for instance clicking the 2nd passphrase registration will trigger an update of the account details from a node (to be sure for instance the 2nd passphrase is not already registered).

**Comment by gmpryb** [comment]
Ohhh I see what you are saying now... So no problems then. Thanks!
