### ISSUE TITLE
Backup reminder & Linking wallet to mobile app

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#22]
Currently there doesn't appear to be a function to backup your passphrase, as i assume if lost you will never be able to access the wallet again.

I think it would be helpful if it reinforced this at the start of creating a wallet and then asks periodically to backup.  I guess as the wallet doesn't sync the whole chain then it doesn't need backing up in the traditional sense?  

Is there future dev to link your desktop ark client to your mobile client?  Will you be able to do that via a QR code.

**Comment by fix** [comment]
yes you can already use qr code to transfer your wallet to mobile wallet. Try it out!

I have not yet included passphrases in the desktop client, because i did not have time to make the secure framework to encrypt passphrases in the app, but will do.

**Comment by jamiec79** [comment]
unfortunately i can't as i i OS wallet hasn't been made available, i'm guessing due to Apples app vetting process. do you have an eta on this iOS wallet?

Thank you

**Comment by Doweig** [comment]
No mobile wallet ATM. Let's delay for now
