### ISSUE TITLE
Price API

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#221]
Why you're using http://coinmarketcap.northpole.ro/ and not the official https://coinmarketcap.com/api/?

At the moment the ArkClient is showing a wrong price:
http://coinmarketcap.northpole.ro/api/v5/ARK.json - 0.000504466
https://api.coinmarketcap.com/v1/ticker/ark/ - 0.00060169

**Comment by fix** [comment]
Agree we should migrate to official API. At the time i coded it, official API was not available. That is why http://coinmarketcap.northpole.ro/ created it.


Fix

**Comment by luciorubeens** [comment]
Fixed #408
