### ISSUE TITLE
Wallet errors 

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/ark-desktop#229]
Well fill out another time......

Within a few days. I have some notes to go over

**Comment by fix** [comment]
🤔

**Comment by alexbarnsley** [comment]
@michaelthecryptoguy 6 days later... how many notes you got? xD

**Comment by michaelthecryptoguy** [comment]
Sorry. Will add them asap. I know of 3, but I need to double check them

**Comment by michaelthecryptoguy** [comment]
I have been using the older wallet version. I haven't download the newer
version (I am now), so the possible fixes I seen may already be fixed.

**Comment by michaelthecryptoguy** [comment]
As of now, I haven't noticed any of the errors I seen on the updated wallet.

**Comment by j-a-m-l** [comment]
@fix, since @michaelthecryptoguy said that he didn't notice any error, this issue might be closed

**Comment by michaelthecryptoguy** [comment]
K

On Sep 22, 2017 9:56 AM, "Juan" <notifications@github.com> wrote:

@fix <https://github.com/fix>, since @michaelthecryptoguy
<https://github.com/michaelthecryptoguy> said that he didn't notice any
error, this issue might be closed

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ArkEcosystem/ark-desktop/issues/229#issuecomment-331454076>,
or mute the thread
