### ISSUE TITLE
Delegate function

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#23]
Will the delegate screen be able to show more information around latency of the delegates server, uptime etc?

When blocks are forged it created coins? Will it show the delegate how many coins have been forged from blocks?

Where does it show the transactions fees earned during forging process?  Will they be highlighted in some way?

**Comment by fix** [comment]
yes

**Comment by jamiec79** [comment]
i've seen a screenshot or two where it shows the transaction earnings whilst forging in the android client, but not currently in 0.1.1 desktop, will that change in future versions

**Comment by Doweig** [comment]
Same comment that in #7 . There's some good features for delegates currently in the explorer and mobile apps. Better to keep the wallet app lean
https://github.com/ArkEcosystem/ark-explorer
https://github.com/ArkEcosystem/ark-android-monitor
https://github.com/ArkEcosystem/ark-ios-monitor
