### ISSUE TITLE
KRW display

### ISSUE THREAD

**Issue by infinitytn** [ArkEcosystem/ark-desktop#232]
Hello

Just saw new version support KRW and korean. Thanks.

1. Comma add to KRW.
In KRW we use comma(,) in every 3 digits. 
E.g) 1,000,000

2. Decimals in KRW
We dont use decimals so just round up is fine.

Thanks

**Comment by luciorubeens** [comment]
Fixed in 606d2d3de8fbcfac74c4a38746551f3acc98099b
