### ISSUE TITLE
MacOS Signature Issues

### ISSUE THREAD

**Issue by segovius** [ArkEcosystem/ark-desktop#238]
Gatekeeper gives the generic warning "Cannot open - is from unknown developer".

Little Snitch gives "The process has no code signature. The executable can be maliciously modified without being detected" when detailing IP outgoings.

**Comment by fix** [comment]
true that, i have not built a signature to transfer to @luciorubeens for the mac build
Will upload new signed build.

As for IP outgoing, it basically regularly polls many ips of the network...

**Comment by luciorubeens** [comment]
Fixed in version 1.5.1
