### ISSUE TITLE
Confirmations

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#24]
Will the desktop client show the number of confirmations required before a transaction of ark is approved?

Similar to other wallets i've used, they also have a link to the blockchain explorer which provides more detailed information

**Comment by fix** [comment]
Yes, i want to make things as simple as possible for non tech people, so basically confirmations is raising more questions than solving issues.

However I am thinking about a special option for advanced users to enable more info and more tools, so all people get their ease in using the client.

**Comment by jamiec79** [comment]
yeah that makes sense, after many years of mining and using wallets, it would be great if there was a advanced user function.  i agree its a fine line between too much and too little info. but and advanced and basic function would work for me.

**Comment by Doweig** [comment]
Let's merge with https://github.com/ArkEcosystem/ark-desktop/issues/32
