### ISSUE TITLE
Ark desktop cannot open after install 

### ISSUE THREAD

**Issue by h2002al** [ArkEcosystem/ark-desktop#240]
I installed version 1.3.2 and tried to open but cannot open. Give "unspecified error. Maybe you don't have permissions to open it". I deleted all the ark files at program files (at exception of exe file and uninstall file which cannot be deleted) and the other files at roaming folder and tried to install it again. This time is showed "error opening file for writing" "...../...../..../uninstall ArkClient.exe". I use windows 10 pro.

**Comment by fix** [comment]
which version did you use? win64?

**Comment by h2002al** [comment]
Yes.

**Comment by fix** [comment]
can you spot if your architecture is win32 or win64?

**Comment by h2002al** [comment]
Where can learn this? I am not an expert only a simple user. :( Show me when can find this data.

**Comment by fix** [comment]
Maybe some missing administrative rights. Sounds like you don't have rights access some files.

**Comment by fix** [comment]
for architecture:
https://www.howtogeek.com/howto/21726/how-do-i-know-if-im-running-32-bit-or-64-bit-windows-answers/

**Comment by boldninja** [comment]
**How can I tell if my computer is running a 32-bit or a 64-bit version of Windows?**
To find out if your computer is running a 32-bit or 64-bit version of Windows

Open System by clicking the Start button The Start button, right-clicking Computer, and then clicking Properties.
Under System, you can view the system type.

**Comment by h2002al** [comment]
Don't think so. I can install and uninstall everything. Then I have installed smoothly all the previous vesrion of ark desktop. No change is made from one to another install.

**Comment by h2002al** [comment]
System type is 64 - bit.

**Comment by h2002al** [comment]
x64 - based processor

**Comment by boldninja** [comment]
Can you try this?
Go to C:\Program Files\ArkClient
1. Start Uninstall ArkClient.exe and uninstall
2. Right click on 'ArkClient Setup 1.3.2.exe' and 'Run as Administrator'
3. Go to C:\Program Files\ArkClient and right click on 'ArkClient.exe' and again 'Run as Administrator'

**Comment by fix** [comment]
sounds like that the install or the download got corrupted. I have no idea how to do it but i guess you need to get rid off those files. How about renaming the installation folder and then redownload/reinstall again?

**Comment by h2002al** [comment]
Bold cannot uninstall. 1. "Windows cannot access the specified device, path or file. You nay not have the appropriate permissions to access the item". 3. I don't have arkclient setup 1.3.2.exe but only arkclient.exe. installed 16 august. All the other files are installed 4 September. When tried to run the above file as administrator give the same as 1. 2. Error opening the file. See above.

**Comment by h2002al** [comment]
Fix the installation folder is the C:\Program Files\ArkClient?

**Comment by fix** [comment]
yes

**Comment by boldninja** [comment]
arkclient setup 1.3.2.exe = installation program to install Ark Client
arkclient.exe = executable file to start Ark client after you install the client

**Comment by h2002al** [comment]
Solved. Now everything is fine. The exe file have been corrupted. :)

**Comment by h2002al** [comment]
Bold I know that. My answer is correct.

**Comment by boldninja** [comment]
Glad it worked out.

**Comment by h2002al** [comment]
Thanks a lot Bold and Fix.
