### ISSUE TITLE
Localisation: Contact Address Hover

### ISSUE THREAD

**Issue by Spikarija** [ArkEcosystem/ark-desktop#244]
There is an error upon mouse hover on the contact addresses list where the popup on top of "i" symbol is displayed in English (Income:.... Expend:...) even if another language is chosen. Attached and emphasized in red.
![popup](https://user-images.githubusercontent.com/31689626/30103361-b45f3458-92f2-11e7-8275-f7736f043180.jpg)

**Comment by fix** [comment]
yes aside from the fact that the words are mismatched:
expend -> income
income -> expense

**Comment by ckhatri** [comment]
Went ahead and fixed that in my PR!

**Comment by luciorubeens** [comment]
Fixed in #246
