### ISSUE TITLE
Localisation: Import Account Dialog

### ISSUE THREAD

**Issue by Spikarija** [ArkEcosystem/ark-desktop#247]
Upon clicking on "Import Account" while a language other than English is chosen the dialog for passphrase entry contains English text instead of a translation, the same goes for "QR CODE" link, both emphasized in red in the attached screencap.

![import account](https://user-images.githubusercontent.com/31689626/30152541-b594c3e4-93b3-11e7-8ad2-b85d16b046a5.jpg)

**Comment by fix** [comment]
thanks for pointing this out.
Reason is that we made a last minute change in this warning and did not update the transalation files for this.

**Comment by Spikarija** [comment]
we can thank hylex for this - if it weren't for his passphrase guessing games I probably wouldn't have noticed

**Comment by luciorubeens** [comment]
Fixed.
