### ISSUE TITLE
Electron 1.8.0 Issue - OSX 10.12.6

### ISSUE THREAD

**Issue by SBero** [ArkEcosystem/ark-desktop#249]
I was working on some of these issues and wanted to see about retrieving any package updates. After installing them, I couldn't get the app to start. 

It would be loading and then nothing would open up and no error messages.

I deleted my entire node_modules after no luck trying to figure out what was happening. Re-installed, still nothing.

Downgrading to 1.7.x, fixed the problem. Have no other machine to validate my issue.

Relavent?
https://github.com/electron/electron/issues/10433

OSX 10.12.6

**Comment by fix** [comment]
mmm i have macosx sierra, will try here. To reproduce, you mean upgrading to electron 1.8.0 breaks (no other package update)?

**Comment by SBero** [comment]
I did an update to all packages. With Electron 1.8.0, I couldn't get the app to launch. Downgrading to either 1.7.5 or 1.7.6 both made it possible to run again.

I also deleted my node_modules directory, and did a fresh npm install, and it didn't work either with 1.8.0.

**Comment by j-a-m-l** [comment]
@SBero are you still having problems?

**Comment by luciorubeens** [comment]
We are currently using `electron@1.7.11`
