### ISSUE TITLE
Feature Request: Store the clients window size on close

### ISSUE THREAD

**Issue by DooblyNoobly** [ArkEcosystem/ark-desktop#256]
On starting the Ark Client the window opens up really big. The client should capture and store the window dimensions before it closes and then reapply the settings on the next use.

**Comment by SBero** [comment]
This feature has been implemented now. Thanks!

**Comment by fix** [comment]
👌

**Comment by leimig** [comment]
Shouldn't this thread be closed? Since it's implemented.

**Comment by luciorubeens** [comment]
Fixed in #257
