### ISSUE TITLE
Desktop Client - Update function

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#26]
Hi

How does the wallet update function work?  Does it automatically update the wallet, i know using 0.1.0 to 0.1.1 you need to download the new version and install.  It does seem to automatically pull in my detail from previous wallet.

Will there be an optional auto update function (or a button to check for newest version, i know in the past with other wallets it could get quite messy having to import private keys etc....

**Comment by Doweig** [comment]
Is there a wallet update feature at the moment?

**Comment by jamiec79** [comment]
no not that i'm aware, but rather than having to install a fresh version and re-key the accounts/delegates. it would be useful if the wallet could flag when there is an update and then install it over the top of the current....

I know that the transactions sit against the delegate, so as long as they have a record of the accounts then re-keying wouldn't be too problematic...

**Comment by Doweig** [comment]
Need to evaluate the security implications on auto update, what if some server get hacked and send fake updates to ask all clients to download his malicious code.
When it comes to crypto, I'm not a big fan of auto updates.
What do you think @fix ?

**Comment by jamiec79** [comment]
I agree there are risk, but the point of the wallet is ease of use and reducing the risk of error, people having to manually update and re-key information increases risk of human error....

how many times have microsoft or apple been hacked and their updates corrupted....

surely there could be a verification of update, back to update server, before i begins any install...

just thinking with the aim being mass adoption and alot of new people to ark/crypto might struggle with wallet updates... just thinking ease of use and ensuring that everyone is using the correct/updated version of the wallet.... otherwise they could potentially get themselves in a mess if running old version of wallet...

anyway you guys are the experts, i was just coming at this from a noob, ease of use perspective....

Thanks

**Comment by Doweig** [comment]
You're right man, auto updates are better when it comes to ease of use.

**Comment by fix** [comment]
Well for lite client should be ok. However it might be difficult to setup.
See https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

**Comment by Doweig** [comment]
Ok, I think I might have the solution
We intend to have an official web wallet in the future. On the web, therefore always up to date 👍 
So people looking for ease of use will go for the web-wallet while people waiting to have more control over the code, network requests and security will use the local desktop one.
What do you think?

**Comment by fix** [comment]
Sounds good.

**Comment by jamiec79** [comment]
agreed.

**Comment by Doweig** [comment]
Ok so I added the client version inside the header https://github.com/ArkEcosystem/ark-desktop/pull/35/commits/08a105e4de885e0e6459316e6fc44e7fd84e4f0c
So it will be easier to see which client you're running on and update if necessary.
Added that we will provide will client on the web later, can I close this issue @jamiec79 ?
