### ISSUE TITLE
Wrong account balance

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#260]
Not sure what was the reason but I was seeing very different balances for my 3 accounts. One of the accounts has ~20% more ARK and the two ~40% less. I had to restart the client a couple of times to see the correct balances. A bad peer? But how it is sending the wrong balances?

Does anyone have experienced the same issue?

**Comment by boldninja** [comment]
Probably a bad peer. Do you maybe have 'force' setting ticked on some server?
If you'd send more Ark than you have it would get rejected by the network (something along account doesn't hold enough funds, ... ) . Maybe @fix can shed more light on this.

**Comment by zillionn** [comment]
Main screen and inside the wallets. It looked like the peer is outdated, maybe those were the balances like 2 months ago. But should I connect to a peer not in sync?

This could be temporary because I believe yesterday there was some issues with the seed servers.
