### ISSUE TITLE
Wallet Improvement with News Feed

### ISSUE THREAD

**Issue by Arckanum1** [ArkEcosystem/ark-desktop#262]
Hi,
On the Homepage of the Wallet, a section that displays the news from the Ark Blog would be great.
As a lot of us don't regularly check the Ark blog, but do check out wallets. The feed could be below the price/network boxes, or off to one side. Would help the Wallet feel more complete/interactive and more than just a Wallet

EDIT: Ok, so I expertly photoshopped a mockup. News on the left side or a news feed on bottom bit:
https://imgur.com/a/8HfGW

**Comment by j-a-m-l** [comment]
I think that it's a good idea :+1:

**Comment by j-a-m-l** [comment]
The idea would be showing the title of the last blog post.

It would be optional, so users could enable/disable it.
