### ISSUE TITLE
User name

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#27]
On the main desktop client it shows on the left hand side my user all in CAPs, yet on the main screen it's all in lower case, i just wondered why?  It's a very very minor point.

**Comment by Doweig** [comment]
Tried on 0.1.1 and my delegate name (account name) is lower case everywhere.
Is this issue still valid?

**Comment by jamiec79** [comment]
i think it may have been the previous desktop client, pre-HD, so i'll have a check when i get home... but i think it may have been fixed when 0.1.1 was released.
