### ISSUE TITLE
Blockchain explorer

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#28]
Hi will the mainnet client have a function to explore the blockchain for your transaction.  I know in the past sometime when a transaction has delayed or been lost it's always been the best place to find out specific information?

Will the main wallet show that a transaction has been successul, i know i asked about confirmations, but is there a green/red flag that can show the transaction status?  are there a number of confirmations required before it's classed as a complete transaction?

**Comment by Doweig** [comment]
Let's merge this issue with https://github.com/ArkEcosystem/ark-desktop/issues/24 together
