### ISSUE TITLE
ArkClient 1.3.2 Took 5Ark with no warning

### ISSUE THREAD

**Issue by Kapla5053** [ArkEcosystem/ark-desktop#285]
There was no warning given that it cost 5Ark to create a second secure word.
I repeat, there was NO WARNING that it would cost 5Ark

I DO NOT WANT A SECOND SECURE WORD IF IT COSTS THAT MUCH

Transaction ID 74f04864bf26518da22e331d5e6c506f09665308ef3ecce6381cc97b0460991f

**Comment by luciorubeens** [comment]
hey @Kapla5053, a confirmation has been implemented and will be released in the next version.

**Comment by Kapla5053** [comment]
And what about all the people who lost 5 ark **without knowing** the cost of creating a second passphrase?

**Comment by boldninja** [comment]
@Kapla5053 you didn't lose it, but you paid for additional security. Fees are written in the whitepaper and on the blog.

**Comment by Kapla5053** [comment]
@boldninja @luciorubeens When you go to a supermarket, are there **no** labels on the groceries and your bank account gets charged as soon as you touch an item while the prices are stated in the blueprints of the supermarket?

**Comment by boldninja** [comment]
That analogy is not the same. If you just touched a grocery you wouldn't have anything, you'd need to take it out thinking its free and then wondering why is someone yelling behind you that you need to pay.  You did receive something when you registered 2nd pass - additional security so its not like you had to pay for clicking a mouse (touching groceries).  Anyway new version will address this with PR : https://github.com/ArkEcosystem/ark-desktop/pull/231 .

**Comment by Kapla5053** [comment]
you'd need to take it out thinking its free and then wondering why is someone yelling behind you that you need to pay

~ If this had happened, i would have the **option** of giving back the groceries that i took... Still:
- No pricetag
- No confirmation
- No refunds
 
UNETHICAL

**Comment by boldninja** [comment]
Blockchain is immutable so there is little to do regarding reversing transactions, else this could be said with all the lost / deleted passphrases that people want reset. You have an option to recover PIN code with bank account, reset GMail pass, ... but with blockchain this is different. 

Anyways fees go to delegates that forge blocks, its not like we are selling anything here. 

All I can say is, I'm sorry there will always be ways to improve stuff and there will always be bugs to fix, there is no perfect software out there just improvements and catching such stuff so it can be addressed and fixed.

**Comment by Kapla5053** [comment]
@boldninja @luciorubeens 
Even if it was a mistake, a good organization would take responsibility for suck a mistake and at least try to refund those who got charged without being informed.

Meanwhile, i'm stuck here with a 15$ tampon that i touched at "the supermarket with no pricetags that takes money directly from customer's bank account". A tampon that I don't need (I'm a single male)
