### ISSUE TITLE
Right click function - copy and paste doesn't seem to work when sending ark to recipient

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#29]
Hi,

The copy and paste function via right click on mouse doesn't work, i can't copy and paste addresses into the destination field. it works via control +C & V, but not via the mouse.

Thanks

**Comment by Doweig** [comment]
Which platform are you running on?
It works here on Mac

**Comment by Doweig** [comment]
Is this bug still valid @jamiec79 ?

**Comment by jamiec79** [comment]
Sorry just tried to check at work and forgot the wallet blurs the screen when remoting in....

I'll have to check when i get home.

**Comment by Doweig** [comment]
Ok, take your time :1st_place_medal:
