### ISSUE TITLE
Document Hashes for Downloads

### ISSUE THREAD

**Issue by danrichman** [ArkEcosystem/ark-desktop#291]
Would be helpful to have hashes in order to verify official downloads for each release.

Something like this:

> ### Hashes
>Mac: aea6c39528f8104c385r4853sd01bd8be0f089a217792092988691eda6fb71e8
`openssl sha -sha256 ArkClient-Macos-1.3.2.dmg`
>
>Windows: b24ca19c9ea2de8e984lofhdo371720325960264188a7e4c3d44b47b5a5ed4f0
`certUtil -hashfile "ArkClient-Win32-1.3.2.exe" SHA256`
>
>Linux (debian): b581c54f9439c304398qieds6ff075db255be18fc7b3ebe473d55802365458cb
`sha256sum ArkClient-Ubuntu-1.3.2_amd64.deb`

(Those are fake/example hashes for anyone wondering)

**Comment by luciorubeens** [comment]
Hi @danrichman, thanks for the suggestion! Added to the latest release.
