### ISSUE TITLE
Improve the testing infrastructure

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/ark-desktop#297]
Currently there are only 4 tests and there isn't any kind of mention anywhere.

I'd like to change that, so with those tests:

- Explain how to start with tests on README
- Change CONTRIBUTING to emphasise the utility of adding tests
- Split the current `test/index.js` into helpers/utils/page-objects to reuse some parts
- Add some additional tests
- Configure a CI

What do you think?

**Comment by j-a-m-l** [comment]
I just started this, but I'm thinking on using [AVA](https://github.com/avajs/ava) instead of Mocha, to take advantage of its concurrency. Since we have just a few tests, would be very inexpensive.

What do you think @luciorubeens @fix ?

**Comment by j-a-m-l** [comment]
Since other [projects](https://github.com/ArkEcosystem/ark-js) are using Mocha, Mocha would be the decision.

**Comment by fix** [comment]
I do completely back this idea. @boldninja we should think about a special bounty for setting up testing and adding some meaningful test (like a test for each issues reported -> bounty)

**Comment by j-a-m-l** [comment]
This could be closed now (#308, #315)
