### ISSUE TITLE
Refactor main HTML file (`index.html`)

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/ark-desktop#298]
Currently this [`index.html`](https://github.com/ArkEcosystem/ark-desktop/blob/master/client/app/index.html) has more than 1000 lines of dense HTML. This file is changed frequently, so it's common that PRs have to resolve conflicts when the main branch is updated.

I'd like to split it in simpler views/directives/components to avoid that problem. Should I?

**Comment by SBero** [comment]
I think that this should definitely be turned into different components/directives. The entire thing can be quite cumbersome to work through.

Going a step further, I also think the app should be using Redux as well.

**Comment by j-a-m-l** [comment]
Yes, @SBero . Working on https://github.com/ArkEcosystem/ark-desktop/pull/315, I've realized that there are lots of small things that are easily broken...

My idea is creating 3-7 new components/directives and moving the big chunk of commented HTML to a different file (is it useful for someone?).
After that, I think that we could refactor everything easily.

**Comment by timart1n** [comment]
After touching in the code myself I completely agreewith you ;)
After taking a look around (im new to all this nodejs, angular, electron thing :p ) I believe it is posible to make a lot of self-contained react modules that produce the current angular code spread out on the html file.
