### ISSUE TITLE
Update to newer versions of Node.js and start using some ES7 features

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/ark-desktop#299]
I think that, since we're using Electron, we could be able to start using newer features of ES without having problems. What do you think?

Other option could be using TypeScript if you're into that...

**Comment by luciorubeens** [comment]
Yeah, @peterdouglas has the same purpose #195. I agree we need to switch to ES6/7, but I think Typescript is not a good choice for angular v1

**Comment by luciorubeens** [comment]
Yes, do it. But please make a new branch and commit step-by-step.

![do-it.gif](https://i.giphy.com/media/jndc0TQq9fvK8/giphy-downsized.gif)

**Comment by boldninja** [comment]
@luciorubeens is turning into true ARKer with meme addiction 😂
