### ISSUE TITLE
AUR pkgbuild .desktop and .png

### ISSUE THREAD

**Issue by ITwrx** [ArkEcosystem/ark-desktop#306]
@luciorubeens i thought i might try to update the pkgbuild and post a link in the aur comments to save you/others some time, but i got nowhere. :) I'm not very well versed in node, electron or npm and i'm not sure where i'm supposed to get the .desktop and the .png (referenced in currently available pkgbuild) from and/or their sha1 sums. It looks like maybe changes were made to the way ark organized it's releases so i'm not sure where to start.
thanks

**Comment by luciorubeens** [comment]
Hey @ITwrx, oh yeah. Would be great if we had the `.desktop` file here. And I think sha1sum is optional, so will remove.
