### ISSUE TITLE
Ark Wallet Equivalent currency next to Balance does not change when clicked on

### ISSUE THREAD

**Issue by exastiken** [ArkEcosystem/ark-desktop#312]
Operating System: Win10

I noticed that the currency would change when clicked on in the previous version, but in the current version it does not do anything except darken when clicked on.

**Comment by luciorubeens** [comment]
Hi @exastiken, i made a fix that will be in the next version

**Comment by luciorubeens** [comment]
Fixed in 9c346b4a5a917837ebaff1eb225247993f953086
