### ISSUE TITLE
transaction tab not updating after sending ark

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#32]
just sent a transaction and it doesn't show in my transaction list, this is the first time i've sent, rather than received, does it take a while to update the desktop client?

the transaction screen doesn't update if you click on transaction tab, but it does when you click your name on the left hand side....

**Comment by Doweig** [comment]
This issue will include transaction status and confirmations updates

**Comment by jamiec79** [comment]
cool that makes sense to me.

Thanks

**Comment by fix** [comment]
Right now it refreshes transaction list every 10s, but improvement could be to add tx in the list while still in unconfirmed state, and poll the network until it gets confirmed. It could be also possible to resend transaction to be sure it gets included in a block.
