### ISSUE TITLE
Set a CI environment on github

### ISSUE THREAD

**Issue by timart1n** [ArkEcosystem/ark-desktop#322]
Hey,

So after tackling with a bit of code on my own I would like to improve the development/merging process with travis + codacy + codecov + shields.io badges, this will bring:

 - Build status
 - Test status
 - Static code analysis
 - Code coverage
 - Quick check and links to details of all the previous ones

As an example you can take a look in this project:
https://github.com/streamingpool/streamingpool-core

Besides having all of these infos in the main page for quick access this also helps on having a better understanding of the impcat of a merge request as you can have the CI execute on the pull for every commit before it is accepted!

**Comment by j-a-m-l** [comment]
I've started that on https://github.com/ArkEcosystem/ark-desktop/pull/315, but some parts require configuration by @luciorubeens or the owners of the repo.

**Comment by luciorubeens** [comment]
Fixed #315
