### ISSUE TITLE
Desktop Client 1.4.0 Discrepancy between "My Accounts" balance and actual Address Balance

### ISSUE THREAD

**Issue by ArkPotato** [ArkEcosystem/ark-desktop#329]
The "My Accounts" balance is showing a greater balance compared to the actual balance on my wallet. For me it is showing a balance 2.6k greater. I have talked to peers and they seem to have the same issue but with a different discrepancy.
Desktop client 1.4.0 on Mac OSX

**Comment by ArkPotato** [comment]
![balance disrep](https://user-images.githubusercontent.com/32655723/31363233-d9432840-ad11-11e7-9483-f4d06fdb4441.jpg)

**Comment by j-a-m-l** [comment]
In the past I've suffer this problem, but now I'm not able to reproduce it.

@ArkPotato could you elaborate more? do you have any contact, delegate, etc?

**Comment by ArkPotato** [comment]
@j-a-m-l 
No contacts, vote for Biz_Classic,  have two wallets one with 0 Balance.

**Comment by luciorubeens** [comment]
@ArkPotato do you have ledger accounts?

**Comment by ArkPotato** [comment]
@luciorubeens no, no trezor or ledger or anything like that. Only thing i've done is Download wallet, Vote, and transfer funds here and there.

**Comment by j-a-m-l** [comment]
I think that I've found the problem!

When the user set the account label to the exact name that a delegate, then the app, gets the balance of the delegate (at least that has produced wrong balances for me on DEVNET).

@ArkPotato do you have uses account labels?

**Comment by ArkPotato** [comment]
@j-a-m-l Unfortunately, no, I do not use any labels

**Comment by yonseiyes** [comment]
I have the same problem... I use account label.

**Comment by liamreoch** [comment]
I've made a PR with a fix for this issue.

**Comment by luciorubeens** [comment]
Fixed in #330
