### ISSUE TITLE
Hit / Miss When Splash Image Shown

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/ark-desktop#331]
Currently there is a "hit and miss" on when image is shown with splash screen.

![splashimage](https://user-images.githubusercontent.com/25795454/31378431-8bc41fc6-adab-11e7-8673-d5df1cc8fbea.png)

Haven't been able to pinpoint on when it doesn't show and when it does.

**Comment by krau612** [comment]
For me, it either loads the entire splash screen (both the "Loading..." and the image) or nothing at all.

**Comment by fix** [comment]
same here

**Comment by luciorubeens** [comment]
Fixed #348
