### ISSUE TITLE
I'm not able to click anything..

### ISSUE THREAD

**Issue by benjammin90** [ArkEcosystem/ark-desktop#334]
I've downloaded the new Ark wallet and I can't click on my wallet or any of the icons. The app doesn't seem to work. The only thing that works is the application and Edit tabs at the top. I'm using the Windows 64 version. The previous version after being downloaded doesn't work either now.

**Comment by boldninja** [comment]
@benjammin90 are you connected to a peer (cloud image)? Try restarting ARK wallet or uninstalling and installing ARK desktop again.

**Comment by fix** [comment]
@benjammin90 did you solve your issue?

**Comment by benjammin90** [comment]
Yes, the newer version 1.4.1 did the trick. Also a computer restart was
necessary.

**Comment by boldninja** [comment]
Great

**Comment by ageorge9625** [comment]
I have a MAC my wallet cloud is red, no firewall setted.
What should I do?

**Comment by RedPlumpTomato** [comment]
Hi all,

I'm having the same issue so decided to upgrade to 1.5.1. Still, can't click anything in the main window, but, the menu at the top works fine.  Quit option doesn't though so I have to end ARK using the task manager. Anybody can shed some light on this?

**Comment by j-a-m-l** [comment]
@RedPlumpTomato 

- could you upload a screenshot of the screen?
- could you press Ctrl+d and copy the text of the console or upload it as a screenshot?

**Comment by RedPlumpTomato** [comment]
It’s ok. Figured it out. I had my ledger plugged in and it was locked.  So unplugged it and all is well.

On Mar 23, 2018, at 1:03 PM, Juan <notifications@github.com<mailto:notifications@github.com>> wrote:


@RedPlumpTomato<https://github.com/redplumptomato>

  *   could you upload a screenshot of the screen?
  *   could you press Ctrl+d and copy the text of the console or upload it as a screenshot?
