### ISSUE TITLE
Screenshot Protection Doesn't Work on Linux

### ISSUE THREAD

**Issue by krau612** [ArkEcosystem/ark-desktop#336]
I'm running Ubuntu Mate 17.04 and the latest version of the wallet. I can still take screenshots with no issues. I think it's an issue with electron, however, because https://electron.atom.io/docs/api/browser-window/ only has macOS and Windows listed for "win.setContentProtection(enable)".

**Comment by fileninja** [comment]
The best place to handle this is in electron for sure.
however, even if we write that function on our own there is no real protection.
what catches me from getting out my smartphone and taking a picture?
nothing.. so in the end the best screenshot protection is to not display any sensitive information.

**Comment by liamreoch** [comment]
@fileninja generally someone is more likely to be aware of a person holding a smart phone and taking a picture than a malicious process taking screenshots in the background.

**Comment by fileninja** [comment]
@liamreoch i agree with you. But the Screenshot protection is no 100% Solution if we talk about Malicious processes. Whats about open an RDP / x11 session and taking a Screenshot of that. this can also be automated. So its always a discussion about Making it harder not Impossible.
