### ISSUE TITLE
Antivirus denied internet connection

### ISSUE THREAD

**Issue by mlsBlue** [ArkEcosystem/ark-desktop#340]
After installing latest version of application, Norton security denied internet connection and I was not able to do anything in the application. Is there any additional work that I need to do.

**Comment by fileninja** [comment]
well, as you mentioned already this is a norton related problem.
as you trust the ark desktop client you can simply tell norton to allow this program trough its firewall.
For instructions you can give the norton support site a look.
https://support.norton.com/sp/en/us/home/current/solutions/v6958602_ns_retail_en_us

**Comment by mlsBlue** [comment]
Thanks for answer it's very common problem with lot applications regarding crypto wallets and miners. I was confused cause for weeks I have installed application and Norton didn't said anything and now all of a sudden there is a problem. I allowed application to use internet connection in Norton. And everything is fine now, as usual.

**Comment by fix** [comment]
here the point is that most crypto wallet open many connections to different peers (as for p2p software). This looks similar to this malware that turn computers into zombie to perform DDoS attacks. That's explains why antivirus try to deny access to internet to the wallets.
