### ISSUE TITLE
Incorrect balance shown on Account screen

### ISSUE THREAD

**Issue by n4ru** [ArkEcosystem/ark-desktop#343]
I'm seeing a significantly different balance from what I actually have after selecting my account.

**Comment by fix** [comment]
did you update to version 1.4.1?

**Comment by fix** [comment]
maybe the dashboard has not refreshed. can you click on the refresh icon and see if it solves?

**Comment by alexbarnsley** [comment]
@n4ru is this the initial screen that lists accounts or the screen that shows your transactions that's wrong?

**Comment by n4ru** [comment]
It is my ledger nano account (I have no other), which does not display balance on the initial screen. I upgraded from 1.3.x and never had the previous balance bug.

**Comment by alexbarnsley** [comment]
Interesting, so it showed the balance of your ledger in 1.3.x? I'm sure I added that functionality into 1.4. I'll test in a bit to see if I can replicate. What happens when you press the refresh button as @fix mentioned? Does the balance show then?

**Comment by n4ru** [comment]
The balance shows, but it's completely incorrect. It was correct before updating.

**Comment by alexbarnsley** [comment]
Very interesting, and you're definitely on 1.4.1? I'll reply back once I've had chance to test

**Comment by boldninja** [comment]
@n4ru previous version didn't yet have Ledger balance reflecting on main screen. Do you have any other wallets added that are not on Ledger? Cause main screen sums all of your wallets you have.

**Comment by n4ru** [comment]
I have an old wallet with no ARK in it. Other than that just the ledger with the bug.

**Comment by j-a-m-l** [comment]
@n4ru could you elaborate a little bit more on the problem? I'll try to reproduce myself

**Comment by n4ru** [comment]
No longer able to reproduce after a fresh install. Perhaps there was something cached left over after updating?

**Comment by j-a-m-l** [comment]
Thank @n4ru for your feedback. I'm going to close the issue, but if it detect it again, you are free to reopen it.
