### ISSUE TITLE
make Toast management as a service

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/ark-desktop#344]
The way to show toast message is a bit chaotic here. A service would be good instead with function like (displayed in level order):
- toastService.error
- toastService.success
- toastService.warn
- toastService.log
- toastService.debug

A config would set level of messaging (default level `success`)

Also the toast events could be logged into some log files for debug for instance

**Comment by alexbarnsley** [comment]
@fix would the toast service show all types of messages? Or is that what you mean by config defaults to success only?

**Comment by spresnal** [comment]
I believe the active level would be used like the example below. Where it toasts for the active level and all levels above.

Ex: 
Level: Error - Toasts for errors
Level: Warn - Toasts warning, success, and error

**Comment by fix** [comment]
yes

**Comment by alexbarnsley** [comment]
Ah okay, I think I understand. So "success" would also show "error" because it's above? That makes more sense to me! My concern was that "success" wouldn't show messages like "disconnected from network". I'll give this a crack if I get time and no one else jumps on it :)

**Comment by alexbarnsley** [comment]
@fix I'm making good progress on this. Any preference on where you want logs to be stored? Also, will the config be loaded from a file or the storageService? Thanks!

**Comment by alexbarnsley** [comment]
@boldninja - I'm not sure if you want to get me specific colours for each notice type? If not, I can wing it. If you do decide to, background colour and font colour for each would be great 😄 thanks!

**Comment by alexbarnsley** [comment]
Initial version of this should be ready by around mid-day tomorrow for you guys to check. I expect some tweaks/changes but will be good to know feedback. @luciorubeens I've implemented a very basic configService which loads config/config.js. I guess you'll see when I create the PR 🙂 I've left all current toast entries as either success or error. Any new ones can pick up the new notice types (warn, log, debug)
