### ISSUE TITLE
Ark desktop wallet update 

### ISSUE THREAD

**Issue by bigbeezy209** [ArkEcosystem/ark-desktop#355]
Hey guys has anyone had a issue updating desktop wallet? I had the previous desktop wallet and clicked on the github link and followed the download instructions. After the new update installed it gave me a error that I didn't have administrative access? The ark desktop icon was a generic image and didn't even load the logo. I tried to reinstall the same update again no luck. I then uninstall the program and try to reinstall but same issue. I'm on windows Vista if that makes any difference. It worked fine before. Once I uninstall the only file left is a locked administrator file in the Ark folder.. I'm lost anything would be a help. Thanks

**Comment by j-a-m-l** [comment]
Please, @bigbeezy209 could you provide more information?

**Comment by bigbeezy209** [comment]
It's my fault I fixed the issue thanks for your response

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexbarnsley** [comment]
@bigbeezy209 are you able to provide the solution that resolved it for you? It could be helpful if someone else who may have the same issue

**Comment by bigbeezy209** [comment]
I just needed to restart my laptop after the installation for some reason it wouldn't allow it to work before.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by j-a-m-l** [comment]
@bigbeezy209 Thanks for replying again
