### ISSUE TITLE
Cant update wallet

### ISSUE THREAD

**Issue by chadballantyne** [ArkEcosystem/ark-desktop#3565]
Hi There!
Trying to update my wallet
Getting an "Unknown Error" pop up

All I can do is close the window

- Version used:2.7.0
- Environment name and version node v12.4.0
- Operating System and version: MAC 10.15.7

![Screen Shot 2021-03-26 at 5 22 10 PM](https://user-images.githubusercontent.com/56271092/112694346-969bef00-8e58-11eb-8d2f-a7dd8555e5f7.png)
![Screen Shot 2021-03-26 at 5 25 04 PM](https://user-images.githubusercontent.com/56271092/112694347-969bef00-8e58-11eb-9ddc-724ae35bda7d.png)

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
**Thanks for opening your first issue in the desktop-wallet repository!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
Hi there, i believe there were some problems with the auto updater in that version, please download 2.9.5 directly from the website https://ark.io/desktop-wallet
