### ISSUE TITLE
lots of rogue processes when running on linux

### ISSUE THREAD

**Issue by zomzilla** [ArkEcosystem/ark-desktop#358]
Using the latest version of Ark wallet on Ubuntu 17.04 results in a large number of processes left running in the background. Below are the results of a quick investigation when starting from a cold boot.

- opening Ark wallet initially results in 6 "ledger-worker" processes being started
- closing Ark client leaves these 6 running as well as the ark client process itself
- opening the wallet again results in another Ark client process as well as another single ledger-worker process

this happens whether closing the window or clicking the quit button within the program. I need to kill all these processes every time i quit as they use a lot of memory when left unchecked.

**Comment by alexbarnsley** [comment]
I believe this has been addressed in PR #357

**Comment by zomzilla** [comment]
I could be totally wrong here, but i'm not sure that addresses the whole issue. 
that fix ends the ledger processes on exit, but why am i seeing 6 of them started in the first instance? also the main Ark client process is not ending either

**Comment by krau612** [comment]
@zomzilla Only one ledger-worker process is ever created. I'm going to assume you're using htop to look at the processes. By default, htop shows threads as well as processes. The things that show up in white are processes and the things that show up in green are threads. You can toggle the threads by pressing shift+h. If you do that, you will see one instance of ledger-worker.

**Comment by zomzilla** [comment]
Looks like I was totally wrong! the ledger process keeping the main open does make sense.
