### ISSUE TITLE
Feature request : Currency 1 and Currency 2

### ISSUE THREAD

**Issue by arkfan** [ArkEcosystem/ark-desktop#359]
Hello,

I've been using the wallet for a while now and I think I would be better if you could choose two currencies in the settings. In the previous releases you had to click on the price to cycle through all available currencies. Now you have to go in the settings to change currency. My idea is a mix of you had in the past and what you have now : you choose two currencies in the settings (not just one) and you switch between those two currencies by clicking on the price. The thing is, as a european, I'm only interested in knowing the price of arks in bitcoins and euros not in just one of the two and not in any other currency.

**Comment by zillionn** [comment]
Or maybe we should completely remove BTC from currencies and always show it, for instance:
Price     $2.48178 (Ƀ0.00042627)
Price     €2.1086071503 (Ƀ0.00042627)

**Comment by Joseph-Tortorelli** [comment]
That would be smarter.  I like that idea.  Do you know how Ark gets its current prices?  Does it call it from a single marketplace or does it take it as an average?

**Comment by zillionn** [comment]
Currently from here:
http://coinmarketcap.northpole.ro/api/v5/ARK.json
