### ISSUE TITLE
Security Blurring of Wallet - Remote or screenshot.

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#36]
The security feature is fine, but can it be permanently selected to be secure or insecure (i.e blurring the image on screenshot).   

It's frustrating that when i remote in i can't use the wallet.....  Rather than having to be at home to disable the security it makes remote accessing of wallet a real pain at the moment.

Unless this function can be permanently switched on or off by the user, i haven't found a way to do that yet.....

It's a great function, but not currently very practical to remember to switch the security off before i leave the house, just in case i might have to remote in....

**Comment by dafty235** [comment]
I would like to see this too and can see it being quite a common problem. Perhaps as a toggle in the settings page?

**Comment by Doweig** [comment]
Yes, this feature has been asked few times, can be quite frustrating. We will add it.

Meanwhile use this:
- Open the console using `ctrl + d`, on Mac `cmd + d`
- Paste in the console `require("electron").remote.getCurrentWindow().setContentProtection(false)` and press enter

The screenshot protection is now disabled until you restart the client

Hope this helps!

**Comment by Doweig** [comment]
Fixed in https://github.com/ArkEcosystem/ark-desktop/commit/33a4d5aa25d7a824d66d8b9d3e8ce0268a637d08

**Comment by Doweig** [comment]
There is a "Disable screenshot protection" feature available from the menu now
