### ISSUE TITLE
Remove account from Ledger

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#360]
Is it possible or we should remove that function?

**Comment by alexbarnsley** [comment]
I don't think so. I think the best case would be the option to have "hidden" accounts that just don't show in the UI. Someone like @fix knows better about the capabilities of ledger, but the way I understand it, all addresses exist already on a ledger, they're just unused. Perhaps in the future it could be developed to "close" and address and move all funds to another address. But it depends what's practical I guess

Out of curiousity, why do you want to remove an account?

**Comment by zillionn** [comment]
I have created several accounts but emptied most of them and now they're just sitting. However, I don't mind that but there is an option "REMOVE" which obviously doesn't work.

**Comment by fix** [comment]
this is UX issue. What other apps do, is that they hide all accounts into a single one and merge balance and transactions into a sigle multi address account. We should do it at some point with the following caveats:
- only show last created address.
- merge (add) balance, and merge transactions into a single list
- sending out ark may results in several transactions (from different addresses). This will be solved with aip11 with multipayment transactions.

**Comment by zillionn** [comment]
@alexbarnsley you want to hide the REMOVE button if Ledger address and earn Ѧ5?

**Comment by alexbarnsley** [comment]
Thanks @zillionn xD I was going to guide you on doing it but it wasn't as simple as I expected (even though it is a 2 line change!

I've done the PR to hide the Remove button now. Maybe you could create a new issue relating directly to @fix's comment, so we don't lose track of that plan. I can create it if you prefer?

Thanks!
