### ISSUE TITLE
[Bug] ArkClient Helper spiking CPU (macOS High Sierra)

### ISSUE THREAD

**Issue by nlpthk** [ArkEcosystem/ark-desktop#364]
Recently my MacBook's fans have been going off and upon inspection via the Activity Monitor, "ArkClient Helper" has been on the top of the CPU processes list

**Comment by krau612** [comment]
This is most likely related to Issue #358 which is resolved by PR #357 .

Can you do me a favor to help confirm this? Can you:
1. Record the CPU usages of ArkClient and ArkClient Helper
2. Close the client
3. Force quit all instances of ArkClient and ArkClient Helper in the Activity Monitor
4. Open the client
5. Record the CPU usages of ArkClient and ArkClient Helper

Essentially, there's a process that continues to run after you close the client. If you have opened and closed the client multiple times without restarting your computer, then multiple instances of this process will be running in the background.

**Comment by j-a-m-l** [comment]
Please, @nlpthk could you confirm that this problem is fixed on the last version?

**Comment by nlpthk** [comment]
Yup! Haven't experienced the problem with 1.4.3:)
