### ISSUE TITLE
Box to right of balance - Default display BTC - 0.3.0

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#37]
The currency box next the the Ark balance shows in BTC value, the value doesn't look correct, you may have not switched on the other currencies for a reason.  But currently nothing other than btc works...when you click to cycle through the currencies...

I know it's test net so the BTC value probably isn't correct.  But in test holding 45.6K ark = 1.5 BTC...

![image](https://cloud.githubusercontent.com/assets/24484606/22822183/3d0b0ee2-ef76-11e6-9d96-199e5e4ae4c2.png)

![image](https://cloud.githubusercontent.com/assets/24484606/22822199/50b4460c-ef76-11e6-95aa-a26271d34754.png)

**Comment by Doweig** [comment]
Yes conversion is not working as there's no exchanges trading ark yet.
I'll put a static rate equivalent to TEC rate.

**Comment by Doweig** [comment]
Fixed in https://github.com/ArkEcosystem/ark-desktop/commit/74ac843483ac18a4a4841041b80628a56263c61f
BTC value will be 0 until after the mainnet release
