### ISSUE TITLE
Wallet blacked out

### ISSUE THREAD

**Issue by junglefever** [ArkEcosystem/ark-desktop#374]
hi guys,  I love the new desktop wallet, but after changing some appearance settings, it is now all blacked out. How can I undo that?

It was all fine till I changed some of the appearance settings (think I was playing around with the Themes)
AlI I get now is a blacked out screen in the Ark Client.  
Disabling the screenshot protection and re-installing doesn't solve the issue.

For now am using the web lite wallet. 
Please advise, 

Thank you

**Comment by luciorubeens** [comment]
Hi @junglefever. Open the wallet and press Ctrl + D, click the Console tab, take a screenshot and send here please

**Comment by junglefever** [comment]
hi Lucio, sure thing!

thanks for the help.

![error_ark](https://user-images.githubusercontent.com/33221925/32177149-cf12efd0-bd89-11e7-8b5b-c1bb5eb733a7.JPG)

**Comment by luciorubeens** [comment]
It looks like there was a problem saving the theme data and it was corrupted.. to restore the data to default you need to run this code: `localStorage.clear();window.location.reload();`

![1 pc6ucdvswyofydtaxafexa](https://user-images.githubusercontent.com/4539235/32178156-cdffbaac-bd6a-11e7-9cba-f1086b9d95ab.jpeg)

**Comment by junglefever** [comment]
that worked beautifully!
Thanks :)

All back to normal now.
