### ISSUE TITLE
Coins Not Received After 7 Hours

### ISSUE THREAD

**Issue by Dalesones** [ArkEcosystem/ark-desktop#378]
Please help:   ARK Destop1.4.1 transaction sent from Bittrex as completed but coins did not receive after 7 hours.

**Comment by alexbarnsley** [comment]
I presume you confirmed the withdrawal in bittrex? What does it say the status is in bittrex? Worth also double checking the address you sent it to. Chances are this isn't a desktop client issue. If you check explorer.ark.io for the address you sent it to, it should show the order if it was successful.
@boldninja you're better at dealing with this sort

**Comment by boldninja** [comment]
@Dalesones check TXID on explorer.ark.io - if its not there, contact Bittrex support, nothing we can do.

**Comment by Dalesones** [comment]
I confirmed that is was sent from Bittrex to my correct address which is correct.  I do have the tracking ID, but don't know where to use it.  d78d5875ab453b4adf7ff5786b2c918851487a133e653b8e7955220e306043ea

**Comment by boldninja** [comment]
That txid doesn't exist on ARK blockchain so you'll need to ask Bittrex via support to rebroadcast it.

**Comment by Dalesones** [comment]
Yes, thank you so much.
