### ISSUE TITLE
Send Transaction Process Alters the Amount Specified!

### ISSUE THREAD

**Issue by Spikarija** [ArkEcosystem/ark-desktop#385]
See attached picture, problem pointed out in red squares; while trying to send an amount I noticed that the client altered it by 1 arktoshi, the resulting total being less than specified:
1. the amount entered was 7 decimals deep, nothing out of the ordinary;
2. the amount in the TX review dialogue was 8 decimals deep and less than what was entered in step 1 (I tried re-doing it with 8 decimals specified i.e. a zero added to the original amount and the result was the same);
3. when the transaction took place it did so with the amount shown in the second dialogue.

Truth be told, I would not have detected this if it weren't for the fact that I'm developing an application that is expecting an exact transaction amount on the recipient side.

I've tried it while connected to Mainnet as well (without committing the TX) and the client behaves the same.
![mysterious arktoshi](https://user-images.githubusercontent.com/31689626/32521681-bc9c6da4-c414-11e7-8e6d-4931105deda3.jpg)

**Comment by j-a-m-l** [comment]
I can confirm this bug, when moving 1.0440473 DARK. I'll fix it ASAP.

**Comment by boldninja** [comment]
I noticed this with trying to send 299.9 it sends 299.8999999

**Comment by j-a-m-l** [comment]
This should be fixed on https://github.com/ArkEcosystem/ark-desktop/pull/387.

Anyway, I'm going to add more unit tests in the near future to avoid this kind of problems
