### ISSUE TITLE
Didn´t recived ARK

### ISSUE THREAD

**Issue by Boricko2** [ArkEcosystem/ark-desktop#390]
Hello,
yesterday i sent ARK from my Bittrex account to my Nano Ledger S and I didn´t recived my ARK´s, could you know where should be a problem?

First I tried to sent small amout of ARK and it works, I recived it so I decided to sent all of my ARKs,.. 

I do the same with other arks but it never come, its 24 hours almost and i am scared that I lost my ARK... :D 

I do the same steps and sent it to the same adress, so where can be a problem? Bittrex is showing that the transaction is completed..

I used Ark client 1.4.1

Thanks for help!

Have a nice day.

**Comment by boldninja** [comment]
You should contact Bittrex support ( https://support.bittrex.com/hc/en-us/requests/new  , your ARKs are not lost if you sent to correct ARK address. Just means your TX didn't hit ARK blockchain and they will need to rebrodcast the TX.

**Comment by Boricko2** [comment]
Thanks!
