### ISSUE TITLE
Balance in some currencies is shown as NaN

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/ark-desktop#391]
![nan balance in currency](https://user-images.githubusercontent.com/1161224/32658552-cbb4a704-c61a-11e7-829e-1c12d84640c6.png)

**Comment by luciorubeens** [comment]
I think the currency value can be hidden in Devnet. The [DARK](http://coinmarketcap.northpole.ro/api/v5/DARK.json) token is DarkCoin, so it does not make sense to show.

**Comment by j-a-m-l** [comment]
That could be an option, @luciorubeens, but if I connect to a new network that has its own token?

**Comment by j-a-m-l** [comment]
I've removed the "Type: Bug" label because now it's more about deciding the behaviour in those cases.

Since connecting to other networks and tokens isn't common yet, we could hide that currency value except when connected to Mainnet.

**Comment by boldninja** [comment]
How about in network adding option for CMC ticker (everything except mainnet) if empty it hides the options?

**Comment by j-a-m-l** [comment]
Thanks @boldninja!

I like that option. I would explore it.
