### ISSUE TITLE
version GLIBCXX_3.4.21 not defined in file libstdc++.so.6

### ISSUE THREAD

**Issue by rpolve** [ArkEcosystem/ark-desktop#395]
Hi,
This might be due to me being a noob, but I've installed from latest .deb package and I'm unable to start arkclient; when I try to do so from terminal, it outputs this:

```
$ arkclient
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.B43Fvq: symbol _ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/ArkClient/resources/app.asar/node_modules/node-hid/nodehid.js:9:15)
    at Object.<anonymous> (/opt/ArkClient/resources/app.asar/node_modules/node-hid/nodehid.js:109:3)
```

My system:

 ```
$ cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
```

**Comment by paurisa** [comment]
Take a look here: https://github.com/typora/typora-issues/issues/504
Hope it helps you!

**Comment by rpolve** [comment]
I gave it a read but I don't know what to do instead of this:

sudo cp node_modules/spellchecker/build/Release/spellchecker.node  /usr/share/typora/resources/app/node_modules/spellchecker/build/Release/

**Comment by paurisa** [comment]
It seems that your error comes from Chromium so try reinstalling it.

**Comment by rpolve** [comment]
Still nothing :(

**Comment by paurisa** [comment]
No idea then, sorry.

**Comment by j-a-m-l** [comment]
@rpolve have you tried the solutions from https://askubuntu.com/questions/777803/apt-relocation-error-version-glibcxx-3-4-21-not-defined-in-file-libstdc-so-6#792471 ?

**Comment by rpolve** [comment]
Yes, I've tried now, but it didn't help (actually they broke apt-get, I spent the last half hour fixing it -- now it seems ok).

**Comment by j-a-m-l** [comment]
@rpolve Could you try the Linux version that isn't a deb package (https://github.com/ArkEcosystem/ark-desktop/releases)?

**Comment by rpolve** [comment]
Yes, I tried, but still no luck; I've installed it on a different machine though, so that's it for now.

However I thank you all for trying to help me :)
