### ISSUE TITLE
Message Signing is broken

### ISSUE THREAD

**Issue by n4ru** [ArkEcosystem/ark-desktop#397]
Steps to reproduce:

1. Create a wallet
2. "Sign" a message.
3. "Verify" produces `Error in your input`. Copying message and manually verifying will give a verification error.

"Verify" seems to work when using the first wallet created on my installation, but any new ones have this issue. Copying the message and trying to manually verify fails regardless of wallet selected. Is the signer defaulting to the first wallet's public key?

**Comment by j-a-m-l** [comment]
I've been able to reproduce it on MainNet.

Apart from that, other problem that I've found is that trying to verify an empty message doesn't trigger any visible error.

**Comment by j-a-m-l** [comment]
@n4ru Could you confirm that those new addresses don't have any ARK or transfer?

That could be the problem: they aren't found on the blockchain because they haven't been stored yet.

**Comment by j-a-m-l** [comment]
I've added a message that would be displayed when the address isn't on the blockchain.
