### ISSUE TITLE
Price doesn't seem to update

### ISSUE THREAD

**Issue by rpolve** [ArkEcosystem/ark-desktop#398]
Price doesn't seem to update on my desktop wallet, whatever the currency, nor am I able to force it to do so.

Arkclient 1.4.1
Ubuntu 16.04.3 LTS

**Comment by j-a-m-l** [comment]
This is related to https://github.com/ArkEcosystem/ark-desktop/issues/221.

**Comment by ckhatri** [comment]
Looks like v5 of the api (which we use) was deprecated October 31st. 
https://www.reddit.com/r/coinmarketcapjson/comments/6wrv72/new_version_v8_is_stable/

Currently whenever I try to query for any /ticker for v8 there's an internal server error at the moment. So you can't get the specific information about any ticker right now. 

If we use the official api https://api.coinmarketcap.com/v1/ticker/ark/ it only gives prices in btc/usd. But we could make multiple requests to get all the currencies using the convert parameter (which only takes one currency), which seems redundant.
