### ISSUE TITLE
 Problem on changing theme

### ISSUE THREAD

**Issue by Ardeshir81** [ArkEcosystem/ark-desktop#399]
HI!
Ark Client is amazing. Thanks : )

I recently changed my wallet's appearance, unfortunately I don't remember what options I exactly selected. If I'm not mistaken, I choose `midnight`, I'm not sure. BTW what happened is that I am unable to interact with the app since then. As soon as I open it I begin to see a completely blank screen.

I took screenshots of what may help you find what the problem is:

![screenshot from 2017-11-14 22-34-08](https://user-images.githubusercontent.com/5755214/32799312-94604d2e-c98c-11e7-8d76-14d30ec77dcf.png)
![screenshot from 2017-11-14 22-35-19](https://user-images.githubusercontent.com/5755214/32799313-94976138-c98c-11e7-88e4-846a8f939bec.png)

Thank you so much : )
Keep up the good work 👍

**Comment by Ardeshir81** [comment]
Would it be possible to assign myself to this ? Thanks

**Comment by alexbarnsley** [comment]
@Ardeshir81 just comment saying you'll take a look at this. Should be enough to stop others jumping on it 😁

**Comment by j-a-m-l** [comment]
I realized that this wasn't OK while working on other tasks, so @Ardeshir81 if you need help I could help you

**Comment by j-a-m-l** [comment]
@Ardeshir81 One of the problems is:

```js
      var properties = $mdTheming.$get().THEMES[theme]
```
instead of
```js
      var properties = $mdThemingProvider.$get().THEMES[theme]
```

**Comment by Ardeshir81** [comment]
Yeah of course! I'm familiar with AngularJS and AngularJS Material. Don't worry `bout it : ) Thanks ! Will fix it as soon as possible
