### ISSUE TITLE
Refresh client

### ISSUE THREAD

**Issue by axenter** [ArkEcosystem/ark-desktop#4]
Add a refresh tab perhaps so people do not need to shutdown and reopen the client to see the deposit that was made to them.
Add refresh option on right click menu

**Comment by axenter** [comment]
Add a refresh tab perhaps so people do not need to shutdown and reopen the client to see the deposit that was made to them.

**Comment by axenter** [comment]
Balance does not update on Clock page after receiving a TX until restarting the APP.

**Comment by 2mdoty** [comment]
Or have it autoupdate in window. Bitcoin and other wallets do this already. It is possible to update window but involves going out of window by clicking client or something and going back into account.

**Comment by 2mdoty** [comment]
clicking on account number/name refreshes, but is not intuitive in interface.
