### ISSUE TITLE
ARK-client 1.4.2 Account balance not updated on main-screen. (macOS. 13.1)

### ISSUE THREAD

**Issue by rdk1979** [ArkEcosystem/ark-desktop#415]
A tiny minor bug:
after installing 1.4.2 and starting it for the first time it showed the previous account-balance. (I did a transaction while 1.4.1 was running last time, but that amount was still included on the balance.)

After restarting the ARK-client it updated and showed the right account-balance on the main-screen.

edit on November 20:
- This happens on Windows 10 and macOS 13.1. 
- This happens every time, not just on the first run after the update to 1.4.2.

**Comment by boldninja** [comment]
Did you click on refresh balances to update the list?

![refreshb](https://user-images.githubusercontent.com/25795454/32986374-936f14e4-ccd0-11e7-9fa9-69ad345585f3.png)

On specific account you also have this (if you have manually refresh enabled in settings):

![refreshaccount](https://user-images.githubusercontent.com/25795454/32986379-b7b431e0-ccd0-11e7-8944-bffd02ff6c98.png)

**Comment by rdk1979** [comment]
@boldninja thanks, but the "problem" is on the -main- screen... you're in the account already on your screenshot. But... on the main screen there's a refresh too, I know. Ok, than it's not a bug, then it's a tiny design flaw I'd say. The refresh procedure or function should be called right after the program starts I'd say, then the account balance is always up to date. But I don't know... there could also be a good reason for this not to be automatic of course.

**Comment by boldninja** [comment]
@alexbarnsley can you confirm if once you start client and get network connection balances are refreshed? Might be good to add if not yet. 
When 1st connection to ARK network = success, call refresh function (only 1 time once it starts).

**Comment by rdk1979** [comment]
@alexbarnsley i can confirm this a bit more now. Each time you start the ARK-client it shows the balance from the last time the ARK-client was run.

I can confirm this to be the case on macOS 13.1, but also Windows 10.

**Comment by alexbarnsley** [comment]
I can confirm it doesn't refresh all accounts on network connection. There is a setting "Settings" > "Refresh accounts automatically?" which runs every 8 seconds by the looks of it, to refresh the current account. However, this is turned off by default.

I will add the functionality to refresh all accounts on network connection 👌

**Comment by rdk1979** [comment]
@alexbarnsley  is this in the 1.4.3 already? i'll check and confirm it...

**Comment by boldninja** [comment]
@rdk1979 Yes

**Comment by rdk1979** [comment]
Confirmed... works perfectly now! Nice little improvement. 

Thanks @alexbarnsley @boldninja
