### ISSUE TITLE
Un-voting broken in 1.4.2

### ISSUE THREAD

**Issue by bradyo** [ArkEcosystem/ark-desktop#422]
If you try to un-vote a delegate, it doesn't show the `-delgate` in the transaction confirmation, and submitting the transaction fails to update vote.

I rolled back to 1.4.1 and was able to un-vote correctly.

**Comment by boldninja** [comment]
Thanks @bradyo, fix was already coded by one of our devs ( #420 ) and hot fix will be released soon

**Comment by bradyo** [comment]
Ah thanks @boldninja. I'll close out this ticket
