### ISSUE TITLE
CPU out of control

### ISSUE THREAD

**Issue by ehrlichja** [ArkEcosystem/ark-desktop#424]
On Ark Client 1.4.2, two of my CPU cores are monopolized by the ArkClient Helper process, even 
with the wallet application not running.

OSX 10.12.6

![screen shot 2017-11-20 at 6 29 57 pm](https://user-images.githubusercontent.com/481499/33051872-e5df1bb0-ce20-11e7-8466-32ef4b61ed94.png)

Is it mining Vertcoin? ;)

**Comment by fix** [comment]
do you use ledger nano s?

**Comment by boldninja** [comment]
This was supposed to be solved in #357  (which is already merged in 1.4.2) :thinking:

**Comment by alexbarnsley** [comment]
I can give it a whirl! Could they be leftover processes from the previous version of the client? When did you last restart your machine?

**Comment by boldninja** [comment]
I was thinking that as well, that they might have been rogue processes from 1.4.1. 
@ehrlichja can you restart your computer and try to reproduce this?

**Comment by ehrlichja** [comment]
I restarted and am running the wallet again, so far I don't see it.
