### ISSUE TITLE
"Passphrase" should be replaced with a different phrase such as "Mnemonic Phrase"

### ISSUE THREAD

**Issue by Joseph-Tortorelli** [ArkEcosystem/ark-desktop#431]
I commonly see people who are confused by what their passphrase is as they do not remember inputting a passphrase as I was when I first saw it after a while after I made my address.

I ended up just inputting random passwords that I thought I had used.

Replacing "Passphrase" with "Mnemonic Phrase" would make it much more easy to understand, especially if it has been awhile since you accessed the wallet and see the word "Passphrase".

Edit: Added some recent issues regarding the wording "Passphrase"

[Lost my ARK password (not passphrase)](https://www.reddit.com/r/ArkEcosystem/comments/7eqiqm/lost_my_ark_password_not_passphrase/dq6rvse/) (12 hours ago)

[Passphrase?](https://www.reddit.com/r/ArkEcosystem/comments/7esf0i/passphrase/) (8 hours ago)

**Comment by j-a-m-l** [comment]
Probably rewording it to something like "mnemonic passphrase" would be a good idea. Maybe even "generated mnemonic passphrase" would be a better, non-ambiguous name.

@boldninja what do you think?

**Comment by ujjwalwahi** [comment]
Or "Passphrase(12 words generated mnemonic passphrase)". I think it'll be better to be more explicit if users are finding it bit confusing.

**Comment by vngrp** [comment]
To give it a proper name, let's look at the word definitions:

**Passphrase**
a sequence of words or other text used to control access to a computer system, program or data.

**mnemonic**
a system such as a pattern of letters, ideas, or associations which assists in remembering something.

**Comparison:**
a sequence of words **<** a pattern of letters
used to control access **<** assists in remembering something

Passphrase seems like a better word for it. Furthermore, people familiar with blockchain are familiar with passphrases. Mnemonic Phrase makes it sound like a special kind of passphrase, which can be confusing. The real problem in the [passphrase?](https://www.reddit.com/r/ArkEcosystem/comments/7esf0i/passphrase/) article was he forgot to type spaces. Which is already solved [here](https://github.com/ArkEcosystem/ark-desktop/commit/36c3f733e28a9cd1dcce817d4223474e36d4dd35). 

Using concise words like passphrase help in clear communication and are part of a well thought out user experience.

**Comment by Joseph-Tortorelli** [comment]
@vngrp 

I think you are confusing Mnemonic and Mnemonic Phrase.

Mnemonic Phrase usually has to do with a sequence of words, not only letters.

**References that use Mnemonic Phrase:**

[Blockchain.info](https://www.reddit.com/r/Bitcoin/comments/16hks7/wallet_recover_mnemonics_now_available_for_new/)

[MyEtherWallet](https://developers.toshi.org/page/recovering-eth-sent-to-testnet-token-wallet)

[Decryptionary Definition of Mnemonic Phrase](https://decryptionary.com/dictionary/mnemonic-phrase/)

A Mnemonic !== Mnemonic Phrase.

A Mnemonic Phrase is used to create a Mnemonic.

**Example Mnemonic Phrase:** **A**nts **H**ave **N**o **F**ear **O**f **I**ce **C**old **B**eer

**Proceeding Mnemonic:** AHNFOICB

**That corresponds with the following:** Astatine (AT), Hydrogen (H), Nitrogen (N), Fluorine (F), Oxygen (O), Iodine (I), Chlorine (Cl), Bromine (Br).

To me, a passphrase sounds likes it user-inputted.

**Comment by j-a-m-l** [comment]
@Joseph-Tortorelli I'm closing this issue because we are rephrasing several texts on v2, if later, you think that the problem persists, please, re-open it.
