### ISSUE TITLE
Ark Desktop Client Archlinux AUR package is outdated

### ISSUE THREAD

**Issue by CryptoMooners** [ArkEcosystem/ark-desktop#433]
As you can see in [this link](https://aur.archlinux.org/packages/ark-desktop/), the version in the AUR repository is 1.2.2.

Since the files used for making the package aren't part of this repository I'am not able to submit a pull request

I modified and fixed (since it contained a little bug) the PKGBUILD so I could update my system. Here is the patch:

```patch
--- PKGBUILD	2017-11-19 13:54:31.831583200 +0100
+++ PKGBUILD	2017-11-22 03:05:45.160868700 +0100
@@ -2,7 +2,7 @@
 _npmname=ArkClient
 _appname=arkclient
 pkgname=ark-desktop
-pkgver=1.2.2
+pkgver=1.4.3
 pkgrel=1
 pkgdesc="Multi Platform Ark Lite Client"
 arch=(any)
@@ -22,7 +22,7 @@
   "$_appname.png"
 )
 sha1sums=(
-  "56872f135d6e0b86adfdd3d72a6c2c4880750c6c"
+  "945c04d6124eb2eb11ba547f0ac9318d112ece12"
   "687295fc60638fdd828646e7fc44eaf38eca3cd0"
   "66dadafaa8f6c03c1790a9fa1acf33ec0bfeaa64"
 )
@@ -38,5 +38,5 @@
   install -Dm644 "$srcdir/$_appname.desktop" "$pkgdir/usr/share/applications/$_appname.desktop"
   install -Dm644 "$srcdir/$_appname.png" "$pkgdir/usr/share/pixmaps/$_appname.png"
 
-  chmod -R ugo+rX $pkdir/opt
+  chmod -R ugo+rX $pkgdir/opt
 }
```

**Comment by Ghosthree3** [comment]
I did the same thing, though I had to also modify .SRCINFO with the new version number and hash. I missed the pkgdir typo though, thanks for that.

**Comment by luciorubeens** [comment]
Hey guys, sorry for my late reply. I updated today for 1.4.3, thanks!
