### ISSUE TITLE
Screen capture protection not working

### ISSUE THREAD

**Issue by Bluffet** [ArkEcosystem/ark-desktop#439]
Yo! 

I just toyed around and noticed that even if the screencapture protection is enabled, the wallet shows. It might be that my OS is old. I'm running MacOS 10.9.5

**Comment by Joseph-Tortorelli** [comment]
Gyazo is blocked.  I know that.

What program are you using to screen capture or is it built in?

**Comment by alexbarnsley** [comment]
I missed this @Bluffet - sorry! Just tidying up. I suspect it is due to the old operating system you are working on, since I'm on 10.13 and it's working on my end. Are you running as a normal installation? I will close this for now, as we also have a v2 wallet in the works which may fix the issue.
