### ISSUE TITLE
Label doesn't work in Ubuntu wallet 1.4.3

### ISSUE THREAD

**Issue by slydamus** [ArkEcosystem/ark-desktop#441]
Label in newest wallet doesn't work. (tested on ubuntu)
When renaming the account in wallet 1.4.3, after wallet restart it still showing label with an address as a name.
Also, when u create new accounts in wallet, it disappear from the list after the wallet restart.

**Comment by j-a-m-l** [comment]
Weird, I've tried myself and I couldn't reproduce the problem. @slydamus could you provide us with additional information?

**Comment by slydamus** [comment]
Someone on ark slack offered a solution.
I removed version 1.4.3 and leave ~/.config/ArkClient directory intact (ubuntu 16.04), and then installed version 1.2.2 that "fixed" the problem, and then I installed again latest 1.4.3 and now it's working fine.
So, now I don't have problematic config files to send it to you, but I will try to recreate the bug and if I will be successful I will contact you.

**Comment by j-a-m-l** [comment]
Thanks @slydamus for publishing the steps.
