### ISSUE TITLE
Sent Ark to my public key

### ISSUE THREAD

**Issue by wayjayth** [ArkEcosystem/ark-desktop#449]
Hi, I wonder what happens when you send Ark to your public key.
I have accidentally sent Ark from my exchange to my public key on my desktop wallet.
Could I potentially lose my Ark?
Thank you!

**Comment by alexbarnsley** [comment]
Hi @wayjayth 

This is actually an unknown. I just tried making a transaction to a public key on devnet using the CLI and the desktop client and they both failed. I think best case, speak to the exchange as the network probably rejected the transaction. It will be in their court I think, on whether they can recover the ARK.

Have you checked their provided transaction ID in an explorer?

Thanks

**Comment by fix** [comment]
the tx is rejected from the blockchain, the funds are not lost

**Comment by alexbarnsley** [comment]
Thanks for confirmation @fix, that's what i suspected 👍

**Comment by wayjayth** [comment]
Thanks a lot Alex and Francois-Xavier for the help! Appreciate it.

**Comment by alexbarnsley** [comment]
No worries! Did the exchange reply back to you @wayjayth?

**Comment by wayjayth** [comment]
Thank you. I haven't actually checked with them yet but I will. Hope it
works out.
