### ISSUE TITLE
windows 7 64bit clipboard copy issue

### ISSUE THREAD

**Issue by cannabanana** [ArkEcosystem/ark-desktop#45]
bcram [9:41 PM] 
btw windows 7 64 bit copy issue on seed passphrase, doesnt copy to clipboard

**Comment by Doweig** [comment]
Ok so I don't have a windows testing evironment. Tried to download a Windows VM but thanks to the Great Firewall, download 4GB through it is just not possible. Postponed for now...

**Comment by Doweig** [comment]
Is it still the case? Just tried on windows 10 64 bits and it copied just fine

**Comment by fix** [comment]
Is this resolved @cannabanana ?
