### ISSUE TITLE
Click area for some buttons aren't consistent

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#46]
When i hover over the Close Desktop wallet button, it doesn't always allow me to click the button....

dependant on where in the box i click i either get the arrow icon (can't click to close) or the hand icon, which does allow me to close the menu....

the other buttons allow you to click anywhere in the button and it respond, the close button doesn't....

if you move the mouse around the Close button you'd should be able to replicate...

I'm using this on windows 64 bit version.

**Comment by Doweig** [comment]
I'm not sure I get it, the boxes and rectangles not square (see screenshot), so you cursor only changes to "hand when you're on top of the rectangle.

<img width="260" alt="screen shot 2017-03-08 at 4 29 21 pm" src="https://cloud.githubusercontent.com/assets/1850848/23695924/6cf01e80-041c-11e7-998c-01833993f142.png">

Can you maybe attach a screenshot / explain to help me understand?

**Comment by jamiec79** [comment]
Hi,

Yeah it's when you click the power icon, it give you options to close, maximise, minimise.... the close button is the one that when you hover over the close button sometimes is an arrow (can't click) sometimes the hand icon... it depends where you click on the close button...

I'll screenshot it later and upload it to the issue 👍

Sent from my iPhone

On 8 Mar 2017, at 08:31, Guillaume Verbal <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure I get it, the boxes and rectangles not square (see screenshot), so you cursor only changes to "hand when you're on top of the rectangle.

[screen shot 2017-03-08 at 4 29 21 pm]<https://cloud.githubusercontent.com/assets/1850848/23695924/6cf01e80-041c-11e7-998c-01833993f142.png>

Can you maybe attach a screenshot / explain to help me understand?

**Comment by jamiec79** [comment]
![image](https://cloud.githubusercontent.com/assets/24484606/23713603/620641a0-041e-11e7-87fe-de630752f442.png)

**Comment by jamiec79** [comment]
the close button, shown above.  Let me know if you need anything more..

thx

**Comment by Doweig** [comment]
So yeah, after installing a Windows VM on my computer I could successfully reproduce the bug (windows 10 64bit).
However this bug doesn't make sense so I suspect a bug in the rendering engine.
Will try with an updated version of electron.

**Comment by Doweig** [comment]
Got it!

**Comment by jamiec79** [comment]
Great 👍
