### ISSUE TITLE
Transfer from bittrex to Ark wallet

### ISSUE THREAD

**Issue by doktor27** [ArkEcosystem/ark-desktop#465]
Hi,

I bought ark at Bittrex and today I downloaded the Ark client.
I made a test transfer from Bittrex to Ark Wallet, It wask ok.
Then I sent rest of my ark coins to my wallet and I didnt see it in my wallet.
Can you help me?

**Comment by boldninja** [comment]
Hi,
did you check if your TXID from withdrawal request is present on ARK blockchain ( https://explorer.ark.io ) ? Did you confirm email from Bittrex for withdrawal?
Else you should contact Bittrex support - https://support.bittrex.com/hc/en-us/requests/new .

**Comment by doktor27** [comment]
Hi,
Thanks for your reply.
I just checked it, I found there only test transfer. 
I am using 2FA, so I confirmed withtrawal by my code.
Do you think it is possible to my ark coins back?

**Comment by boldninja** [comment]
Of course, just contact Bittrex support and they'll rebroadcast your transaction.
