### ISSUE TITLE
Link to Voting Article on Vote Page

### ISSUE THREAD

**Issue by ckhatri** [ArkEcosystem/ark-desktop#479]
A user on reddit recommended adding a link to an explanation of voting on the voting page. I think its a good idea

https://www.reddit.com/r/ArkEcosystem/comments/7lifs8/official_wallets_should_have_an_explanation_of/

Was thinking of adding this link: https://blog.ark.io/how-to-vote-or-un-vote-an-ark-delegate-and-how-does-it-all-work-819c5439da68.

To the bottom of the voting page. What do y'all think? Wanted to see if there was support before adding this.

**Comment by j-a-m-l** [comment]
It's a very good idea.

@boldninja Apart from that link to our blog (which is perfectly clear), do you have any suggestions of other texts or links to include?

**Comment by j-a-m-l** [comment]
This is solved in https://github.com/ArkEcosystem/ark-desktop/pull/491
