### ISSUE TITLE
One-time passwords?

### ISSUE THREAD

**Issue by aleclarson** [ArkEcosystem/ark-desktop#480]
Is it worth considering "one-time password" support? Or does that not provide extra security for desktop wallets (since the secret key would be stored locally)?

[This library](https://www.npmjs.com/package/notp) looks like it could work (and no dependencies).

**Comment by j-a-m-l** [comment]
I don't have experience implementing it, but, as you pointed, it wouldn't be very secure if it's storing the key in the same computer than the wallet.

**Comment by j-a-m-l** [comment]
@aleclarson I've closed this question because isn't an actionable task. If you want to provide more info about how to use it, you could re-open this issue.
