### ISSUE TITLE
ARK and NEO addresses are too similar

### ISSUE THREAD

**Issue by dwarrier** [ArkEcosystem/ark-desktop#489]
Hi,

I accidentally sent ARK coins to a NEO address, since the client considered it to be a valid address. I'm assuming my coins are lost for good. However, I would like to make sure others don't run into this issue in the future. Is there any way to prevent this (e.g. by giving a warning if the destination address doesn't have any transaction history?)

**Comment by fluorine** [comment]
> by giving a warning if the destination address doesn't have any transaction history?

I think this is quite a good idea. It also helps users of cold storage wallets, to encourage them they check twice their cold wallet address.

**Comment by j-a-m-l** [comment]
After filling the form to send ARK, there's a confirmation step with all the relevant information. Adding a new confirmation should be unnecessary.

Instead of your suggestion of triggering a warning if the destination address is empty, we could show it in that confirmation page. We could check that is an existent ARK address, or even a NEO one, and show different text depending on the case.

IMHO is a very uncommon problem, so this issue would be a not urgent enhancement. @boldninja what do you think?

**Comment by dwarrier** [comment]
Either one of these solutions sounds like it would prevent this issue in the future, thanks for the prompt replies!

**Comment by Nasicus** [comment]
Personally I also think it's better if we show to the user that something _could_  be wrong. I'm also active in a big facebook group and I see often people who accidentally send stuff to wrong addresses (e.g. BTC to LTC and stuff like that).

I gave this a little try and it now looks like this (when the address is not valid, you cannot even click next)
![1](https://user-images.githubusercontent.com/1086065/34477401-467cc144-ef9a-11e7-9ea3-058c7f0c317b.PNG)

If the address is valid, but has no transaction, an info text is shown:
![2](https://user-images.githubusercontent.com/1086065/34477411-576f4184-ef9a-11e7-81d8-27da4ab2de38.PNG)

What do you think? Shoul I create a PR for this or do you guys find it unnecessary.

**Comment by j-a-m-l** [comment]
Yes, IMHO we should use that kind of input status + message more.

The killer feature would be checking that it's a NEO address already.

**Comment by Nasicus** [comment]
Will try that. i can probably simpy use their API (new service in angular).

**Comment by j-a-m-l** [comment]
This is fixed in https://github.com/ArkEcosystem/ark-desktop/pull/499
