### ISSUE TITLE
Sign with Ledger button does not show ?

### ISSUE THREAD

**Issue by littlepaullittle** [ArkEcosystem/ark-desktop#492]
ARK Version 1.4.3 does not display the "sign with ledger" button. It worked before, but now it is not possible to send ARK token to Ledger Nano S. Any ideas ?
thanks, thomas

**Comment by alexbarnsley** [comment]
Please make sure you have only 1 application open using the Ledger. Reboot your machine if necessary to make sure everything is closed and not being accessed.

**Comment by littlepaullittle** [comment]
did so. all reboot. no apps running. Strangely when trying to send coins from Ledger TO Ark account, the "sign with ledger" does display. But not the other way round. Any other thoughts ? Thanks ever so much, thomas

**Comment by boldninja** [comment]
Wait you are trying to send from normal ARK address that is not associated with Ledger with Ledger?

**Comment by boldninja** [comment]
'Sign with Ledger' is only for ARK addresses that are associated with your Ledger, not ARK addresses you generate normally.

**Comment by littlepaullittle** [comment]
Nope, sorry for my poor explanation. I'm trying to send the coins which I are on the ARK address (in the ARK account) to my private ledger address. Exactly how it is described by the manual. And it did work in the past. In this direction the sign does not display. Thus I can not send the coins to my ledger address. However, when trying to send ARK coins from the ledger address to eg. the ARK address (ARK account) the "sign with ledger" button is displayed.

**Comment by alexbarnsley** [comment]
The "sign with ledger" only applies when sending from a Ledger device. If you're sending from a normal ARK address, you need your passphrase.

**Comment by littlepaullittle** [comment]
Thank You so much. It did work and I apologize for mixing things up. Thank You, Thomas

**Comment by alexbarnsley** [comment]
No worries, glad you got it sorted!
