### ISSUE TITLE
Add help text to votes tab

### ISSUE THREAD

**Issue by dafty235** [ArkEcosystem/ark-desktop#50]
Voting is an important part of keeping the network secure.

Currently the Votes tab is looking quite scarce and it's not obvious what the page should be used for.

Could we add a help textbox above the Vote / Add Delegate button with a brief explanation of what voting is, and how to vote?

**Comment by Doweig** [comment]
Right, user education is important, especially when it come to voting.
Contributions about the help content are welcomed

**Comment by dafty235** [comment]
Very rough and ready, but perhaps something like this?

> Voting is an optional, but important mechanism that keeps the Ark network secure.
The 51 delegates with the most votes from the network are responsible for verifying and forging transactions into new blocks.
This page can be used to cast your vote for a delegate that you support.
For more information on the importance of delegates and how the voting mechanism works, click here.
