### ISSUE TITLE
Ledger Nano S - not showing up in Ark Desktop

### ISSUE THREAD

**Issue by TakeitEasyAlan** [ArkEcosystem/ark-desktop#512]
Hi,

I have installed the Ark app on the ledger nano S, and opened the app and disable browser. 
The Ledger Nano works fine with Ripple & ETH.
I have open closed the app on the ledger (and hear a bling, when it is opened again). 
I have also restarted the Ark Desktop application (version 1.5.0) but as you can see below the Ledger Nano Wallet is not shown, any ideas I followed the instructions from the ledger website and watched a few you tube video's and I believe I am doing exactly the correct thing?

So any ideas? 

Thanks in advance, Alan

![image](https://user-images.githubusercontent.com/9886931/34798460-71fb83fa-f65c-11e7-95c0-615da97c1307.png)

**Comment by alexbarnsley** [comment]
Hi,

The most common cause of this is that there is another ledger application open at the same time (e.g. Ledger Manager and ARK Client together). The ledger doesn't like 2 applications running at once. Before continuing, could you confirm there's only the ARK wallet running? A good way to do this could be to restart/logoff to make sure everything is closed properly.

Thanks

**Comment by boldninja** [comment]
@TakeitEasyAlan Make sure Ledger Manager or any other Ledger wallet (other than ARK desktop wallet) isn't running.

If that doesn't help on Ledger when you open ARK app go to settings -> browser compatibility -> must be 'off'

**Comment by TakeitEasyAlan** [comment]
Cheers will try this as I think the Ledger manager was still running as I add the ARK app to the ledger :-)

**Comment by alexbarnsley** [comment]
No worries! I will close for now but if it's still an issue then please re-send so we can keep investigating 😁

**Comment by TakeitEasyAlan** [comment]
Thanks it worked :-)
I have asked Ledger to add it to their documentation, that only one application at a time should be used, so others will not have the same issue :-)

**Comment by alexbarnsley** [comment]
@TakeitEasyAlan yeh good thinking. A lot of people have the same issue as you. It got me recently too and it's the first thing I usually suggest to people with Ledger issues.
