### ISSUE TITLE
Errors of POST requests are not displayed (affects sending and voting)

### ISSUE THREAD

**Issue by doublehelix24** [ArkEcosystem/ark-desktop#518]
**Update:**
When an error in sending or voting (or any POST request really) occurs the UI does not show any message. I.e. you can click through the sending/voting wizards and after that just _nothing_ happens. No error message, no green confirmation either, just nothing.

I propose that those POST error messages should be displayed in order to help the user solve the issue.
For example, if I set my computer's clock to 1 minute in the future I get the silent failure. In the dev console I see a helpful error message in response to the POST request. Reading that would help many users whose clocks might be slightly off.

In my case the error was caused by my proxy server's settings related to the X-FORWARDED-FOR header - but I imagine any network issue (or even a temporary server issue) would be affected.
**/Update**

Voting does not work in the Windows 64 Bit 1.5.0 Version: The two wizard pages work normally but after the final "SEND A1 NOW" button the wizard disappears and nothing happens. No TX is created and no feedback, neither positive nor negative, appears.
The issue is repeatable - it never works.

Doing the _exact_ same process with the exact same wallet on the Linux 64 Bit 1.5.0 Version **does** work.

More info:
* Peer Status is green, current block height and delay of 120ms
* Windows' clock is accurate

I can provide more info and do tests.

![image](https://user-images.githubusercontent.com/17807858/34908790-f4f52e2e-f895-11e7-9377-de720b7a6f0c.png)

**Comment by Nasicus** [comment]
Just tested on Devnet with Windows 10 x64. It works for me.
Can you open the Dev console (`CTRL + D` or via the edit menu) and see if there's an error?

**Comment by alexbarnsley** [comment]
Just make sure the wallet is definitely connected to a peer at the time of sending the transaction

**Comment by doublehelix24** [comment]
@alexbarnsley Yeah, peer status was green, block height up to date and delay was shown as 120ms (i.e. normal).

@Nasicus Will do. Need to get DEVNET ARKs first since my real wallet now _has_ voted thanks to the Linux version and I don't want to waste real ARKs.

**Comment by Nasicus** [comment]
Just click on the "Wifi"-Icon on top to switch the network.
And here you can create a DARK account with 50 DARK: https://kristjank.github.io/dark-paperwallet/

**Comment by doublehelix24** [comment]
Aha, the dev console shows an Internal Server Error:

dependencies.min.js:1 POST http://159.89.92.13:4002/peer/transactions 500 (Internal Server Error)

It does happen with every server I try, so I don't think it's a serer problem per se. To wit:

dependencies.min.js:1 POST http://45.76.39.61:4002/peer/transactions 500 (Internal Server Error)
dependencies.min.js:1 POST http://213.32.9.98:4002/peer/transactions 500 (Internal Server Error)
etc

The exact same servers _do_ work from linux. So I guess its some sort of incompatibility, maybe created by the some region settings in the OS or something of that sort.

I'll try to debug later, gotta run now.

**Comment by Nasicus** [comment]
When you're back you can try the following:

Go to the "Network" ab in the dev tools, find the 500 request , click on it and then click on headers and make a print screen smiliar to this (**ensure you're on the dev net to not expose any sensible information**):

![image](https://user-images.githubusercontent.com/1086065/34909308-0b52fea4-f89f-11e7-8a79-605a6f250ad4.png)

Also go to the "Resposne" tab on the request and tell us what you can see there :)

**Comment by doublehelix24** [comment]
Okay, found the issue:

The response from the server says:
`{"status":false,"error":"Object didn't pass validation for format ip: unknown: #/ip"}`

The reason is that the Windows 10 machine is configured to use my network's proxy server (squid-3.5.26). When I configure windows to not use the proxy server it works.

Here's the full output:
![image](https://user-images.githubusercontent.com/17807858/34909583-4e371bb0-f8a4-11e7-963f-a5a8147cff6d.png)
(The data shown is from DEVNET - future readers can spare themselves the trouble of trying to snoop money)

I'll look into my squid configuration if there's a way to make it "more transparent". 
However I think it would be good if the Ark Client would _display_ the error. That feedback would be valuable - currently the user is left guessing.

**Comment by zillionn** [comment]
@doublehelix24 And can you send transaction?

**Comment by zillionn** [comment]
Can you check your Squid settings if "forwarded_for" is on?

**Comment by doublehelix24** [comment]
@zillionn: Indeed, forwarded_for was _off_ and switching to _on_ fixes the problem.

This bug then really isn't a fault of the ark client. But I think it would be a good improvement to display if the POST to /transactions fails (for any reason). What do you think?

**Comment by alexbarnsley** [comment]
I agree there should be some feedback on the transaction failing to send due to a local network fault. Maybe rename the git issue and edit your original comment at add the additional information, for anyone that then picks it up. Nice work on finding the cause of the issue all!
