### ISSUE TITLE
"Type an address or a name" but only an address is accepted.

### ISSUE THREAD

**Issue by n4ru** [ArkEcosystem/ark-desktop#520]
Haven't actually tested with previous versions, but it looks like the client no longer allows sending to names as of the newest version - it gives the error "The address is not valid!".

**Comment by Nasicus** [comment]
Just tested it. It always acted like that.

But I agree with you: You should proabably even be able to just type the name of a contact and it should be valid and be resolved.

**Comment by n4ru** [comment]
I was thinking more about delegate names, but that too.

**Comment by zillionn** [comment]
You can't use delegate name to send ARK, only contacts.

**Comment by n4ru** [comment]
That's the problem, you should be able to since it resolves to an address just fine.

**Comment by Nasicus** [comment]
I personally agree that it would be nice. HOWEVER we'd need to ensure that no conflicts occur, e.g. if you have a contact with the same name as a delegate. Then we'd need to show a warning / error message.

**Comment by zillionn** [comment]
If you connect to a bad peer it could resolve you a bogus delegate's address. Always use address.

**Comment by alexbarnsley** [comment]
I agree with @zillionn. It should be contacts only. If you regularly send to a delegate then you can add them as a contact, because then you've effectively approved the address

**Comment by n4ru** [comment]
@zillionn I did not consider that, good catch.

@alexbarnsley Right. I guess contacts should still be resolvable by name when sending.
