### ISSUE TITLE
[Bug] [Version 1.5.0] Voting doesn't work for wallets with 2nd passphrase 

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/ark-desktop#526]
First report: https://www.reddit.com/r/ArkEcosystem/comments/7qpaiz/im_having_trouble_with_voting_with_second/

Voting on 1.4.3: 
![](https://i.gyazo.com/c95a73b6192e6da5391b014b5cd65404.png)

Voting on 1.5.0:
![](https://i.gyazo.com/d6bc1df3f394d1cd53745adff7c9847f.png)

Bug introduced on https://github.com/ArkEcosystem/ark-desktop/pull/491

**Comment by luciorubeens** [comment]
Thanks for opening the issue, I'll close this because it was already opened on #525.
