### ISSUE TITLE
There seems to be no way to add contacts via click vs copy/paste

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/ark-desktop#530]
The UX forces one to copy and paste usernames and addresses to add an address.

This is silly. 

When browsing transactions make it easy to click to add users/addresses to the contact list, without having to resort to copy/paste.

This is also a potential security issue in case something is monitoring the system paste buffer.

**Comment by zillionn** [comment]
There is an option to edit it but it should check if it's not in your contacts and show add icon.

**Comment by alexbarnsley** [comment]
I believe this has been addressed in #470. But will take a further look just to be sure
