### ISSUE TITLE
Error: 'missing sender second signature' when voting.  v1.5.0

### ISSUE THREAD

**Issue by 21stcn** [ArkEcosystem/ark-desktop#535]
Cannot vote if have 2nd passphrase in v1.5.0

1.     Votes tab -> VOTE
2.     Select a delegate
3.     Enter main passphrase
4.     It gives transaction details in popup, but no where to use 2nd passphrase
5.     Go SEND A1 NOW
6.     Error: Missing sender second signature

Even if I save the transaction offline, go SEND and import it, there is no place to use the 2nd passphrase when voting through the client.

**Comment by Nasicus** [comment]
Fixed in #525 . They will release a new version soon :)
