### ISSUE TITLE
Split autocomplete addresses into tabs

### ISSUE THREAD

**Issue by plzpickausername** [ArkEcosystem/ark-desktop#537]
![](https://i.imgur.com/WpKXGhp.png)
 -> check this img.

this way much better user friendly ui

also i have wrong send cus not Separation with myaccount and contact

plz change this .

**Comment by Nasicus** [comment]
In my opinion this is unnecessary.
I already partially addressed this in #524.
When you choose an wallet or a contact you now always see something like this:

Contact:
![image](https://user-images.githubusercontent.com/1086065/35410960-4fbd8bfa-0217-11e8-88d1-b0bfe8d2ff24.png)

Account/Wallet:
![image](https://user-images.githubusercontent.com/1086065/35410978-5e236c3c-0217-11e8-8a2e-be04426169b1.png)

**Comment by plzpickausername** [comment]
Nasicus//
my account and contact is very diffrent thing

some time i want send my account to my account.
then im very sure i dont want see my contact address

if i send wrong then never can back

so. Split  is realy need

**Comment by zillionn** [comment]
@Nasicus You could just add a line "Contacts" before the contacts and "My Accounts" before accounts.

<img width="682" alt="screen shot 2018-01-26 at 00 54 46" src="https://user-images.githubusercontent.com/3462869/35416885-9a3c2dbe-0233-11e8-95be-7d62fd104d03.png">

**Comment by Nasicus** [comment]
How about using different symbols? It's non intrusive and also will be the same way in ark-mobile:
![image](https://user-images.githubusercontent.com/1086065/35427807-e57b4246-026b-11e8-8801-22f0b02cc959.png)

(For consistency i would also use the wallet icon on the other places in the app)

**Comment by zillionn** [comment]
Yes, it looks good.

**Comment by j-a-m-l** [comment]
I think that using a different icon is a good idea.

**Comment by j-a-m-l** [comment]
This issue is closed because a different solution has been implemented
