### ISSUE TITLE
ArkClient.exe parameter to enable/disable Screenshot protection

### ISSUE THREAD

**Issue by fbz76** [ArkEcosystem/ark-desktop#540]
Scenario:
When launching ArkClient.exe, the application starts by Defalut with Screenshot Protection Enabled. You can disable it opening the Application top-left Menu.
![image](https://user-images.githubusercontent.com/35872694/35473871-5a5e2356-0386-11e8-9a43-1de85772bb49.png)
Issue: 
In the case you have your server or remote computers running wallets in your own LAN, and you are used to access the server via a remote client (RemoteDesktop, VNCViewer) in your won secure environment, you are not able to view the application when Screenshot Protection is Enabled. See the below example where the black area is the ArkClient.
![image](https://user-images.githubusercontent.com/35872694/35473938-5d4960f2-0387-11e8-8152-59178424a465.png)
This means that you need to connect a physical monitor/keyboard/mouse to your remote server to deal with the ArkClient.
Solutions:
1. Having the possibility to pass to ArkClient a config parameter (i.e, "DisableScreenshotProtection") that is allowing you to start the application: "_ArkClient.exe -DisableScreenshotProtection_"
or
2. Allowing the ArkClient to register the last user choice and apply it again at next ArkClient launch.

**Comment by Nasicus** [comment]
Good idea!

Implemented it via a parameter. Normal users don't need this and this way it cannot be forgotten to turn off ("you need to know what you're doing").

**Comment by luciorubeens** [comment]
Seems good, however this could make the wallet vulnerable

**Comment by Nasicus** [comment]
Why / how do you mean? (Assuming we do it via a parameter).
On Linux we don't even have protection implemented (or is this there ensured in another way?)

**Comment by luciorubeens** [comment]
Someone can install a malicious software to change the shortcut and take screenshots. Currently the option is disabled when restarting/closing the application. But I'm just predicting the worst case scenario..

**Comment by alexbarnsley** [comment]
I agree with Lucio. Someone could make a shortcut/wrapper and replace the original application to launch with the extra argument. Anyway round the protection could be used by someone externally as a way of disabling it themselves.

In Windows for example, I can create a shortcut of an exe, add the --disablescreenshotprotection argument and replace any existing shortcuts with this new one.

@luciorubeens would you say the screenshot protection is to hide accounts, or to hide passphrases, or both?

I think a different route to go down would be to install the wallet on an encrypted USB and use it at the workstation you're at @fbz76, but that's just my opinion.

**Comment by Nasicus** [comment]
Well the question is, if anyone really targets the Ark client _specifically_ and manages to get on your computer, if we can even do anything at all. I highly doubt that in cases like this the screenshot protection will really help a lot.

**Comment by j-a-m-l** [comment]
So, any decision about this?
