### ISSUE TITLE
Initial genesis account has a balance of -125000000 ARK

### ISSUE THREAD

**Issue by dafty235** [ArkEcosystem/ark-desktop#55]
Watch only: AewxfHQobSc49a4radHp74JZCGP8LRe4xA

![image](https://cloud.githubusercontent.com/assets/24987593/24229177/42ae051a-0f70-11e7-8554-239ef7924647.png)

**Comment by fix** [comment]
yes that is the point of premine

**Comment by Doweig** [comment]
Yes, it might look odd at first but that the effect of premine. 125,000,000 create out of this block.
Verbose is good sometimes
