### ISSUE TITLE
This prevents other apps to be hidden using command+h when Ark is open

### ISSUE THREAD

**Issue by gabrielbull** [ArkEcosystem/ark-desktop#557]
There is actually no need for it, electron should have command+h working by default on the app.

https://github.com/ArkEcosystem/ark-desktop/blob/e9b320b53360b279cd199b93c1055653f8441d42/main.js#L288

**Comment by alexbarnsley** [comment]
This seems related to #69. I suspect cmd+h wasn't working, as it wouldn't have been added otherwise 🤔

**Comment by gabrielbull** [comment]
Well, someone should dig deeper but blocking system wide cmd+h to have it work in Ark is a terrible workaround 🤣

**Comment by gabrielbull** [comment]
I would do it but I don't have time, if someone wants to do it, [here's how it should be done](https://electronjs.org/docs/api/menu#main-process).

Basically, you need different app menu for macOS (darwin). With these as the first menu:

```
{
    label: app.getName(),
    submenu: [
      {role: 'about'},
      {type: 'separator'},
      {role: 'services', submenu: []},
      {type: 'separator'},
      {role: 'hide'},
      {role: 'hideothers'},
      {role: 'unhide'},
      {type: 'separator'},
      {role: 'quit'}
    ]
  }
```
