### ISSUE TITLE
Long delay (visually) before anything happens when selecting a new network

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/ark-desktop#560]
Switching from MAINNET to DEV for example, makes one think the action did not go through, so while you click the menu again.. the delay expires and refreshed the entire screen.

Makes for poor UX.

Indicate something is happening or speed up switching.

**Comment by Nasicus** [comment]
Just a side note: If you have a fast connection & the peers are not slow, you barely ever notice this. However I agree that it's still nice to show a loading indicator.
