### ISSUE TITLE
[1.5.1] Verify Text modal shouldn't have a scrollbar 

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/ark-desktop#581]
When verifying a message in text form, the modal should show all the fields without a scrollbar, there's no reason to have a scrollbar there. It's confusing, initially I thought it was missing the other fields until I realized I had to scroll up.

![GIF](https://im2.ezgif.com/tmp/ezgif-2-f4f54e3549.gif)

https://gyazo.com/a255a3e3119503f6cc0a88d5a197bc35

**Comment by j-a-m-l** [comment]
Fixed by #583
