### ISSUE TITLE
[1.5.1] Ledger wallets don't support signing/verifying messages

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/ark-desktop#582]
Ledger wallets should be able to verify/sign messages just as regular wallets. At the moment, the `SIGN / VERIFY MESSAGE` is hidden on ledger wallets.

**Comment by agilob** [comment]
I just tried to unvote on an address from ledger and I get error that I dont have enough ARK to vote. Is that related? Do I need ARK on address to unvote?

**Comment by alexbarnsley** [comment]
@agilob not related to this issue, but I'll respond anyway. Regardless of if you're using a ledger or not, it does cost 1 ARK to unvote for a delegate. There are plans to change the way this is done in AIP11, but in the meantime people often suggest sending the ARK to a new wallet and voting again, as that costs 0.1 ARK.

**Comment by Joseph-Tortorelli** [comment]
Wrote an issue about it awhile back.

Its already labeled an issue.  Someone can close this issue.

#264

**Comment by vmunich** [comment]
Seems like this isn't supported by Ledger yet. Will close this issue.
