### ISSUE TITLE
Usability issue: icon for 'remove' in 'action panel' for wallet may be confused with 'close' action

### ISSUE THREAD

**Issue by woutercox** [ArkEcosystem/ark-desktop#589]
Concerning Ark Desktop Wallet for Mac OSX - version 1.51.

In the Ark Desktop Wallet, if you press the "three dots" menu in the top right, you get an overlay. The 'Remove' icon looks like a 'close' icon because of the cross. Users might mistakenly press it wanting to close the panel.

Possible improvements are:
- move it to a less prominent location - for example the far right of the panel 
- and/or change the icon to something more recognizable like a trash bin icon

![image](https://user-images.githubusercontent.com/26142482/38326867-2ca03f12-3847-11e8-88cc-dd5493e45d3c.png)

**Comment by alexbarnsley** [comment]
@woutercox is the above screenshot intentional? The wallet has "protection" on windows and Mac. If you screenshot on the Mac, it does something interesting and screenshots the window behind it. You can disable screenshot protection in one of the menu's

**Comment by woutercox** [comment]
@alexbarnsley thanks, I did not know and was actually struggling with that.

**Comment by alexbarnsley** [comment]
No worries! It's a learning curve! Let us know if you need anything, will leave this issue as I've not actually looked into it :eyes: thanks!
