### ISSUE TITLE
sending tx to self shows red instead of gray 

### ISSUE THREAD

**Issue by cannabanana** [ArkEcosystem/ark-desktop#61]
small bug not super important.  sending tx to yourself shows as red on the desktop wallet but should be gray.

**Comment by fileninja** [comment]
the send ark button is always red.. not just for sending to yourself.
So what should be done here?

**Comment by luciorubeens** [comment]
@fileninja is on transactions list, total column

**Comment by luciorubeens** [comment]
Fixed in #235
