### ISSUE TITLE
Invalid transaction timestamp

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#65]
Hi,

Sometimes when I send ARKs I get the following message:
**Error: Invalid transaction timestamp**

However, I can see the transaction in the transactions tab with 0 confirmations. Restarting the client doesn't remove it, it disappears only when I make a successful transaction.

For some reason I can't screenshot the ArkClient window, it captures the desktop like the window is transparent. I'm using Mac OS 10.11.6.

**Comment by boldninja** [comment]
Error: Invalid transaction timestamp  - update your OS clock  http://www.macinstruct.com/node/92 and restart Ark client.

For screenshot you need to disable protection (its a security feature if someone would remotely login to your computer they couldn't see Ark client screen). To disable it click in the upper left menu - application - Disable screenshot protection (unsafe).

Make sure you have Ark client version 1.1.0.

**Comment by zillionn** [comment]
Hi,

I use 1.1.0 and I believe my clock is pretty accurate, it's set to auto update from time.euro.apple.com. Could be a temporary issue, I'll let you know if this happens again.

Yeah, I forgot about the screenshot protection...
