### ISSUE TITLE
Mac OS

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#69]
Hi,

I'm using ark-desktop on Mac OS and there are 2 really awkward things: 
- The default window size. When I open the app I resize the window but it doesn't remember it, I have to resize it every time.
- Can't use Cmd+H to hide the window.

**Comment by fix** [comment]
This is not supported yet.
- at start the window positioning is hard coded
- I am not sure electron (the framework we use for windowing) support Cmd+H

**Comment by zillionn** [comment]
https://github.com/electron/electron/blob/master/docs/api/accelerator.md

**Comment by fix** [comment]
the relevant part of doc:
https://electron.atom.io/docs/api/app/#apphide-macos

**Comment by zillionn** [comment]
Even better.
