### ISSUE TITLE
Seeing top delegates

### ISSUE THREAD

**Issue by axenter** [ArkEcosystem/ark-desktop#7]
Can we make a section to see top delegates from the wallet? (assuming that’s in the works)
When you register a delegate the account address in the left menu doesn’t change to it nor does icon so you need to quit and restart the app for changes to take an effect
Can we get a list of all the delegates so you can just mark each one rather than add them 1 by 1 via add delegate
Currently no way to see registered delegates to vote for.

**Comment by axenter** [comment]
Can we get a list of all the delegates so you can just mark each one rather than add them 1 by 1 via add delegate
Currently no way to see registered delegates to vote for.

**Comment by fix** [comment]
there is a "open delegate monitor" button to help so far, but would be better to have it integrated

**Comment by Doweig** [comment]
I'm a big fan of the unix philosophy is software engineering

https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well 

Especially "Do_One_Thing_and_Do_It_Well", `ark-desktop` should be a good wallet and `ark-explorer` should be a good explorer.

**Comment by soliury** [comment]
@Doweig +1
