### ISSUE TITLE
`peer: None` in Network menu

### ISSUE THREAD

**Issue by Nigui** [ArkEcosystem/ark-desktop#733]
**Platform (please complete the following information):**
 - OS: macos mojave
 - Version Desktop Wallet 2.0.0

**Describe the bug**
When starting wallet on mainnet (and devnet), the network menu (bottom/left) does not show the current peer IP or status connection. 

**How to reproduce the bug**
1. Open desktop wallet 2.0.0
2. open network status menu (bottom/left)

**Expected behaviour**
Would be great to show the current connected peer, to know that user is connected. 

**Screenshots**
![image d ios](https://user-images.githubusercontent.com/6088236/49931511-4850c500-fec7-11e8-98a7-a61d3fcb6a75.jpg)

**Comment by boldninja** [comment]
I think that was resolved and will be included in upcoming release of the wallet.

@alexbarnsley can you confirm?
