### ISSUE TITLE
Cold wallet not sending funds!!

### ISSUE THREAD

**Issue by markfoster123a** [ArkEcosystem/ark-desktop#75]
When I try send funds from my Ark Client - 1.0.1 cold wallet account to any other account it comes up with a message saying I have not enough ark for to send (i've even tried sending 1). My address is (AZnR1e1JSmVus9s1nzpp3NbqCZTQ746QgR) i have at least 2000 ark on the explorer so I'm not sure why I can't spend them. Thank you, Mark

**Comment by boldninja** [comment]
Update to 1.1.0 https://github.com/ArkEcosystem/ark-desktop/releases

Also make sure that nethash ( click on that gear icon - manage networks ) is set as

6e84d08bd299ed97c212c886c98a57e36545c8f5d645ca7eeae63a8bd62d8988

You can set seed server as https://node1.arknet.cloud:4001   and UNTICK that force parameter (so its OFF).

**Comment by markfoster123a** [comment]
Hi, thanks I just tried all of those but it still said not enough ark :/

**Comment by boldninja** [comment]
But its showing in wallet when you import your ark address? If you are and want to send everything you need to deduct 0.1 ARK from maximum you want to sell cause of the ARK fee looking at your ark address https://explorer.ark.io/address/AZnR1e1JSmVus9s1nzpp3NbqCZTQ746QgR  you have 2269.8 so maximum you can send is 2269.7

**Comment by markfoster123a** [comment]
I've imported my wallet but the ark isn't displayed in the balance. it says at the bottom "this is a cold wallet. It has never interacted with the network". 
The funds show up only in the explorer.

**Comment by boldninja** [comment]
Are you importing the correct wallet ? Is the address the same in that address field?

**Comment by markfoster123a** [comment]
Yes, exactly the same it's been copied and pasted!

**Comment by boldninja** [comment]
You must have some settings wrong : https://blog.ark.io/how-to-install-reinstall-ark-desktop-wallet-testnet-89c905ff6db8 can you follow ONLY the part of clearing cache (don't change nethash or anything else) just CTRL+D and that line to flush local storage. After that click on +import address and input your passphrase again.

**Comment by markfoster123a** [comment]
It worked. Thanks so much!

**Comment by boldninja** [comment]
No problem ;) enjoy!
