### ISSUE TITLE
Homepage reload button

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#76]
When I receive some ARKs the balances on the homepage is not getting updated and I have to restart the whole client. Why don't you replace the close (X) button in the title bar with reload and when you click it update all balances?

![123](https://cloud.githubusercontent.com/assets/3462869/25072568/7b39d1ca-22da-11e7-91b5-62874dbc1ece.jpg)

**Comment by fix** [comment]
agree +1
