### ISSUE TITLE
Sending amount

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#78]
Not sure why but I can't send certain amounts. For instance, when I type these numbers the amount field becomes red/invalid: 1.1, 2.2, 2.3, 5.1, 40.2, 40.3, 40.7, 40.8 ...

**Comment by fix** [comment]
mmm can't reproduce here, can you screenshot?

**Comment by zillionn** [comment]
After you typed the number did you go to the next field? For me it becomes red/invalid only after I unfocus/go to the next field.

![screen shot 2017-04-20 at 10 15 46](https://cloud.githubusercontent.com/assets/3462869/25218131/64c17e40-25b2-11e7-8b35-466cddb2c709.png)
![screen shot 2017-04-20 at 10 15 57](https://cloud.githubusercontent.com/assets/3462869/25218133/6838233a-25b2-11e7-9b4c-9fd51dee5c74.png)
![screen shot 2017-04-20 at 10 16 08](https://cloud.githubusercontent.com/assets/3462869/25218138/6af23bec-25b2-11e7-944c-36b11eaaa9a0.png)
