### ISSUE TITLE
Unclear: This account has never interacted with the network. This is a cold wallet

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-desktop#83]
It is completely unclear to most new users what that should mean.
I think we would be better of without that information for the "grandma" user.

We should at least change it to something like: There were not transactions yet.
Most will not understand "Cold Wallet". It sounds like broken to them.

**Comment by fix** [comment]
Yes true, it should be rephrased not to look scary.

**Comment by mody199610** [comment]
@fix This Should be closed now not confuse anyone

**Comment by Jarunik** [comment]
We get questions about it in slack every day.
