### ISSUE TITLE
Fiat/btc value of Ark is not available in Linux

### ISSUE THREAD

**Issue by velkysef** [ArkEcosystem/ark-desktop#88]
When I run the wallet on Linux (Xubuntu 16.04) fiat value shows:
![pasted image at 2017_04_25 08_39 pm](https://cloud.githubusercontent.com/assets/5190880/25402534/436dedfa-29f9-11e7-97d8-e4655e6e564f.png)

BTC shows:
![image](https://cloud.githubusercontent.com/assets/5190880/25402648/ab6d7fb0-29f9-11e7-9fbf-5f385ba14fb8.png)

At first I thought this feature was not working at all. But when I tried the wallet on Windows, it worked properly. So it's probably OS related issue.

**Comment by fix** [comment]
Hi this means that somehow the request on the server to retrieve price failed.
Could you try ctrl+R to see if solves the issue?

**Comment by velkysef** [comment]
Hi! No, that didn't work. But everything else seems to be working ok - it's connected to the network, I see my current balance, latest transactions are synced, etc.
Guys on Slack say it's working fine in Ubuntu 16.04 and 17.04
Maybe a better overall picture.
![image](https://cloud.githubusercontent.com/assets/5190880/25405141/a4f74aa4-2a02-11e7-99e0-e59f4aeef1bc.png)
![image](https://cloud.githubusercontent.com/assets/5190880/25405184/c98a3eee-2a02-11e7-94c0-c31ee299a63c.png)

**Comment by fix** [comment]
ah! update to version 1.1

**Comment by velkysef** [comment]
:flushed: 
that helped! thanks

**Comment by fix** [comment]
👍
