### ISSUE TITLE
Ark Icon on taskbar when wallet is loaded

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/ark-desktop#89]
The Ark Icon looks great on the taskbar when sitting on your desktop not loaded or open. But when you open your wallet, it is hard to see the A for the ark symbol. I think it is due to no background (Or clear). This is on your taskbar, where your icons for your applications are.

**Comment by fix** [comment]
can you add a screenshot? Can't understand the exact issue

**Comment by michaelthecryptoguy** [comment]
I think the Icon needs a background.
![Ark Icon background needed](https://cloud.githubusercontent.com/assets/24502401/25778880/2e9c888a-32d9-11e7-9809-a7fd4ab6b00e.jpg)

**Comment by fix** [comment]
true that, on ubuntu/debian there is likely some settings i forgot to set for this taskbar icon.
