### ISSUE TITLE
0 confirmations

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#99]
Not sure what happened sent 1500 ARK and I see 0 confirmations but the transaction went through. In my wallet the txid is:
6a8e111b25088d4dae67bc3005844b146bc37681b449e11f323fcd050ae8ae5f - 0 confirmations
But the other wallet received them with different txid:
d4389681777a3e546f29796c9f568f4b795b0d17ffcc8cd02623886b81617a33

<img width="730" alt="screen shot 2017-05-05 at 01 09 52" src="https://cloud.githubusercontent.com/assets/3462869/25727102/0f74c756-3130-11e7-8787-decac081ecbe.png">

<img width="729" alt="screen shot 2017-05-05 at 01 10 07" src="https://cloud.githubusercontent.com/assets/3462869/25727107/165420c6-3130-11e7-9fec-967fc2bd6c6d.png">

**Comment by zillionn** [comment]
Today I see both transactions, the 0 confirmations still there.

![screen shot 2017-05-05 at 12 11 25](https://cloud.githubusercontent.com/assets/3462869/25739768/ff6dfdc6-318b-11e7-978c-b59e5a400bcc.png)

**Comment by boldninja** [comment]
@zillionn do you use 1.2.0 version of the client?

**Comment by zillionn** [comment]
Yes.

**Comment by boldninja** [comment]
@zillionn did you by any chance send this with 0 conf with version 1.1.0 and upgraded to 1.2.0 after that? BTW try sending 0.1 ARK to yourself - should clear that 0 conf from your list if it wasn't broadcasted successfully.
@fix you have any input on this?

**Comment by zillionn** [comment]
No ninja, I sent them yesterday with 1.2.0.

I know how to clear it but wanted to report this.

**Comment by boldninja** [comment]
Great @zillionn  maybe @fix will have something to say on this - thank you for reporting!

**Comment by fix** [comment]
yes, this is not supposed to happen again. Any chance to have more information about it.

Will add some extra things to rebroadcast after a tempo

**Comment by zillionn** [comment]
Well, as I said, not sure what exactly happened, but I know I did 2 transactions quite fast. Also they are from a delegate account, not sure if that's important.

**Comment by boldninja** [comment]
Shouldn't matter if its from delegate account - Did it stay at 0 confirmations or did it disappear or got broadcasted after that?

**Comment by zillionn** [comment]
It's still 0 but I haven't sent anything after that.

**Comment by fix** [comment]
should be fixed with this https://github.com/ArkEcosystem/ark-desktop/commit/7cc16de3914f678cc5b3bc6a3f10963196ca70d9
